0. SETUP

In [1]:
!pip install pypdf

import nltk
nltk.download("punkt")
nltk.download("punkt_tab")

!pip install rank_bm25

!pip install -q transformers accelerate

Collecting pypdf
  Downloading pypdf-6.21.1-py3-none-any.whl.metadata (7.6 kB)
Downloading pypdf-6.21.1-py3-none-any.whl (405 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.1/405.1 kB 8.0 MB/s eta 0:00:00
Installing collected packages: pypdf
Successfully installed pypdf-6.21.1

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Collecting rank_bm25
  Downloading rank_bm25-0.2.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from rank_bm25) (2.1.3)
Downloading rank_bm25-0.2.2-py3-none-any.whl (8.6 kB)
Installing collected packages: rank_bm25
Successfully installed rank_bm25-0.2.2

In [52]:
!pip install -q bitsandbytes accelerate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 13.0 MB/s eta 0:00:00

Model Setup

In [53]:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import torch


model_name_v3 = "Qwen/Qwen2.5-7B-Instruct"


# 4-bit quantization so the 7B model fits comfortably on Colab GPU
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True
)


tokenizer_v3 = AutoTokenizer.from_pretrained(
    model_name_v3
)


generation_model_v3 = AutoModelForCausalLM.from_pretrained(
    model_name_v3,
    quantization_config=quantization_config,
    device_map="auto"
)


print("Loaded:", model_name_v3)

config.json:   0%|          | 0.00/663 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/27.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

Loaded: Qwen/Qwen2.5-7B-Instruct

In [2]:
from sentence_transformers import SentenceTransformer

In [3]:
checkpoint = "sentence-transformers/all-MiniLM-L6-v2"
model = SentenceTransformer(checkpoint)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [4]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

generation_model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(generation_model_name)

generation_model = AutoModelForCausalLM.from_pretrained(
    generation_model_name,
    torch_dtype=torch.float16 if torch.cuda.is_available() else torch.float32,
    device_map="auto"
)

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.09GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [5]:
from sentence_transformers import CrossEncoder

checkpoint_2 = "cross-encoder/ms-marco-MiniLM-L-6-v2"
reranker = CrossEncoder(checkpoint_2)

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.33k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

In [49]:
def generation(
    query,
    context_items,
    generation_model,
    tokenizer
):
    if not context_items:
        return "I do not know based on the provided documents."

    context_parts = []

    for item in context_items:
        context_parts.append(
            f"""
Document: {item["document"]}
Page: {item["page"]}
Text:
{item["text"]}
"""
        )

    context = "\n\n".join(context_parts)

    prompt = f"""
You are a question-answering assistant.

Answer the question using only the information explicitly supported by the provided context.

Rules:
1. Use only information that is directly supported by the context.
2. Do not add explanations, assumptions, or facts from your own knowledge.
3. Include all important information from the context that is relevant to the question.
4. Do not combine separate pieces of information in a way that changes their meaning.
5. If the context contains an equation or formula, reproduce it only if it is explicitly shown in the context.
6. Do not create, derive, reconstruct, or modify equations or formulas.
7. If different passages describe related but different concepts, keep them separate.
8. If the context does not contain enough information to answer the question, say:
   "I do not know based on the provided documents."
9. Keep the answer concise and directly focused on the question.

CONTEXT:
{context}

QUESTION:
{query}

ANSWER:
"""

    messages = [
        {
            "role": "user",
            "content": prompt
        }
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt"
    ).to(generation_model.device)

    with torch.no_grad():
        outputs = generation_model.generate(
            **inputs,
            max_new_tokens=300,
            do_sample=False
        )

    generated_tokens = outputs[0][
        inputs["input_ids"].shape[1]:
    ]

    answer = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

    return answer

Indexing Functions

In [6]:
from pypdf import PdfReader

doc_list = ["/content/1706.03762v7.pdf","/content/2405.07987v5.pdf","/content/NeurIPS_ML4PS_2025_87.pdf"]

def load_document(documents_list):
  text = []
  for doc in documents_list:
    reader = PdfReader(doc)
    for i,page in enumerate(reader.pages):
     text.append( {
          "document":doc,
          "page" : i+1,
          "text":page.extract_text()
      })
  return text

In [7]:
import re

def cleaning(documents_list):
  cleaned_results = []
  for doc in documents_list:
    text = doc["text"]
    if text is None:
      continue
    text = text.strip()
    if text == "":
      continue
    text = re.sub(r"[ \t]+", " ", text)

    # Reduce 3+ newlines to 2
    text = re.sub(r"\n{3,}", "\n\n", text)

    cleaned_results.append({
            "document": doc["document"],
            "page": doc["page"],
            "text": text
        })

  return cleaned_results

In [8]:
from nltk.tokenize import sent_tokenize

def chunk_documents_sentences(document_list, chunk_size=1000):
    results = []

    for doc in document_list:
        page_text = doc["text"]
        sentences = sent_tokenize(page_text)

        current_chunk = []
        chunk_id = 0

        for sentence in sentences:

            # If chunk is empty, add the sentence first
            if not current_chunk:
                current_chunk.append(sentence)
                continue

            current_text = " ".join(current_chunk)

            if len(current_text) + len(sentence) + 1 <= chunk_size:
                current_chunk.append(sentence)

            else:
                results.append({
                    "document": doc["document"],
                    "page": doc["page"],
                    "chunk_id": chunk_id,
                    "chunk_text": " ".join(current_chunk)
                })

                chunk_id += 1

                last_sentence = current_chunk[-1]

                current_chunk = [last_sentence, sentence]

        # Save final chunk
        if current_chunk:
            results.append({
                "document": doc["document"],
                "page": doc["page"],
                "chunk_id": chunk_id,
                "chunk_text": " ".join(current_chunk)
            })

    return results

In [9]:
load = load_document(doc_list)
clean = cleaning(load)
chunks = chunk_documents_sentences(clean, chunk_size=1000)
print(chunks)

[{'document': '/content/1706.03762v7.pdf', 'page': 1, 'chunk_id': 0, 'chunk_text': 'Provided proper attribution is provided, Google hereby grants permission to\nreproduce the tables and figures in this paper solely for use in journalistic or\nscholarly works. Attention Is All You Need\nAshish Vaswani∗\nGoogle Brain\navaswani@google.com\nNoam Shazeer∗\nGoogle Brain\nnoam@google.com\nNiki Parmar∗\nGoogle Research\nnikip@google.com\nJakob Uszkoreit∗\nGoogle Research\nusz@google.com\nLlion Jones∗\nGoogle Research\nllion@google.com\nAidan N. Gomez∗ †\nUniversity of Toronto\naidan@cs.toronto.edu\nŁukasz Kaiser∗\nGoogle Brain\nlukaszkaiser@google.com\nIllia Polosukhin∗ ‡\nillia.polosukhin@gmail.com\nAbstract\nThe dominant sequence transduction models are based on complex recurrent or\nconvolutional neural networks that include an encoder and a decoder. The best\nperforming models also connect the encoder and decoder through an attention\nmechanism. We propose a new simple network architecture, the Transformer,\nbased solely on attention mechanisms, dispensing with recurrence and convolutions\nentirely.'}, {'document': '/content/1706.03762v7.pdf', 'page': 1, 'chunk_id': 1, 'chunk_text': 'We propose a new simple network architecture, the Transformer,\nbased solely on attention mechanisms, dispensing with recurrence and convolutions\nentirely. Experiments on two machine translation tasks show these models to\nbe superior in quality while being more parallelizable and requiring significantly\nless time to train. Our model achieves 28.4 BLEU on the WMT 2014 English-\nto-German translation task, improving over the existing best results, including\nensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task,\nour model establishes a new single-model state-of-the-art BLEU score of 41.8 after\ntraining for 3.5 days on eight GPUs, a small fraction of the training costs of the\nbest models from the literature. We show that the Transformer generalizes well to\nother tasks by applying it successfully to English constituency parsing both with\nlarge and limited training data. ∗Equal contribution. Listing order is random.'}, {'document': '/content/1706.03762v7.pdf', 'page': 1, 'chunk_id': 2, 'chunk_text': 'Listing order is random. Jakob proposed replacing RNNs with self-attention and started\nthe effort to evaluate this idea. Ashish, with Illia, designed and implemented the first Transformer models and\nhas been crucially involved in every aspect of this work. Noam proposed scaled dot-product attention, multi-head\nattention and the parameter-free position representation and became the other person involved in nearly every\ndetail. Niki designed, implemented, tuned and evaluated countless model variants in our original codebase and\ntensor2tensor. Llion also experimented with novel model variants, was responsible for our initial codebase, and\nefficient inference and visualizations. Lukasz and Aidan spent countless long days designing various parts of and\nimplementing tensor2tensor, replacing our earlier codebase, greatly improving results and massively accelerating\nour research. †Work performed while at Google Brain. ‡Work performed while at Google Research.'}, {'document': '/content/1706.03762v7.pdf', 'page': 1, 'chunk_id': 3, 'chunk_text': '‡Work performed while at Google Research. 31st Conference on Neural Information Processing Systems (NIPS 2017), Long Beach, CA, USA. arXiv:1706.03762v7 [cs.CL] 2 Aug 2023'}, {'document': '/content/1706.03762v7.pdf', 'page': 2, 'chunk_id': 0, 'chunk_text': '1 Introduction\nRecurrent neural networks, long short-term memory [13] and gated recurrent [7] neural networks\nin particular, have been firmly established as state of the art approaches in sequence modeling and\ntransduction problems such as language modeling and machine translation [ 35, 2, 5]. Numerous\nefforts have since continued to push the boundaries of recurrent language models and encoder-decoder\narchitectures [38, 24, 15]. Recurrent models typically factor computation along the symbol positions of the input and output\nsequences. Aligning the positions to steps in computation time, they generate a sequence of hidden\nstates ht, as a function of the previous hidden state ht−1 and the input for position t. This inherently\nsequential nature precludes parallelization within training examples, which becomes critical at longer\nsequence lengths, as memory constraints limit batching across examples.'}, {'document': '/content/1706.03762v7.pdf', 'page': 2, 'chunk_id': 1, 'chunk_text': 'Aligning the positions to steps in computation time, they generate a sequence of hidden\nstates ht, as a function of the previous hidden state ht−1 and the input for position t. This inherently\nsequential nature precludes parallelization within training examples, which becomes critical at longer\nsequence lengths, as memory constraints limit batching across examples. Recent work has achieved\nsignificant improvements in computational efficiency through factorization tricks [21] and conditional\ncomputation [32], while also improving model performance in case of the latter. The fundamental\nconstraint of sequential computation, however, remains. Attention mechanisms have become an integral part of compelling sequence modeling and transduc-\ntion models in various tasks, allowing modeling of dependencies without regard to their distance in\nthe input or output sequences [2, 19]. In all but a few cases [27], however, such attention mechanisms\nare used in conjunction with a recurrent network.'}, {'document': '/content/1706.03762v7.pdf', 'page': 2, 'chunk_id': 2, 'chunk_text': 'In all but a few cases [27], however, such attention mechanisms\nare used in conjunction with a recurrent network. In this work we propose the Transformer, a model architecture eschewing recurrence and instead\nrelying entirely on an attention mechanism to draw global dependencies between input and output. The Transformer allows for significantly more parallelization and can reach a new state of the art in\ntranslation quality after being trained for as little as twelve hours on eight P100 GPUs. 2 Background\nThe goal of reducing sequential computation also forms the foundation of the Extended Neural GPU\n[16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building\nblock, computing hidden representations in parallel for all input and output positions.'}, {'document': '/content/1706.03762v7.pdf', 'page': 2, 'chunk_id': 3, 'chunk_text': '2 Background\nThe goal of reducing sequential computation also forms the foundation of the Extended Neural GPU\n[16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building\nblock, computing hidden representations in parallel for all input and output positions. In these models,\nthe number of operations required to relate signals from two arbitrary input or output positions grows\nin the distance between positions, linearly for ConvS2S and logarithmically for ByteNet. This makes\nit more difficult to learn dependencies between distant positions [ 12]. In the Transformer this is\nreduced to a constant number of operations, albeit at the cost of reduced effective resolution due\nto averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as\ndescribed in section 3.2.'}, {'document': '/content/1706.03762v7.pdf', 'page': 2, 'chunk_id': 4, 'chunk_text': 'In the Transformer this is\nreduced to a constant number of operations, albeit at the cost of reduced effective resolution due\nto averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as\ndescribed in section 3.2. Self-attention, sometimes called intra-attention is an attention mechanism relating different positions\nof a single sequence in order to compute a representation of the sequence. Self-attention has been\nused successfully in a variety of tasks including reading comprehension, abstractive summarization,\ntextual entailment and learning task-independent sentence representations [4, 27, 28, 22]. End-to-end memory networks are based on a recurrent attention mechanism instead of sequence-\naligned recurrence and have been shown to perform well on simple-language question answering and\nlanguage modeling tasks [34].'}, {'document': '/content/1706.03762v7.pdf', 'page': 2, 'chunk_id': 5, 'chunk_text': 'End-to-end memory networks are based on a recurrent attention mechanism instead of sequence-\naligned recurrence and have been shown to perform well on simple-language question answering and\nlanguage modeling tasks [34]. To the best of our knowledge, however, the Transformer is the first transduction model relying\nentirely on self-attention to compute representations of its input and output without using sequence-\naligned RNNs or convolution. In the following sections, we will describe the Transformer, motivate\nself-attention and discuss its advantages over models such as [17, 18] and [9]. 3 Model Architecture\nMost competitive neural sequence transduction models have an encoder-decoder structure [5, 2, 35]. Here, the encoder maps an input sequence of symbol representations (x1, ..., xn) to a sequence\nof continuous representations z = (z1, ..., zn). Given z, the decoder then generates an output\nsequence (y1, ..., ym) of symbols one element at a time.'}, {'document': '/content/1706.03762v7.pdf', 'page': 2, 'chunk_id': 6, 'chunk_text': 'Given z, the decoder then generates an output\nsequence (y1, ..., ym) of symbols one element at a time. At each step the model is auto-regressive\n[10], consuming the previously generated symbols as additional input when generating the next. 2'}, {'document': '/content/1706.03762v7.pdf', 'page': 3, 'chunk_id': 0, 'chunk_text': 'Figure 1: The Transformer - model architecture. The Transformer follows this overall architecture using stacked self-attention and point-wise, fully\nconnected layers for both the encoder and decoder, shown in the left and right halves of Figure 1,\nrespectively. 3.1 Encoder and Decoder Stacks\nEncoder: The encoder is composed of a stack of N = 6 identical layers. Each layer has two\nsub-layers. The first is a multi-head self-attention mechanism, and the second is a simple, position-\nwise fully connected feed-forward network. We employ a residual connection [11] around each of\nthe two sub-layers, followed by layer normalization [ 1]. That is, the output of each sub-layer is\nLayerNorm(x + Sublayer(x)), where Sublayer(x) is the function implemented by the sub-layer\nitself. To facilitate these residual connections, all sub-layers in the model, as well as the embedding\nlayers, produce outputs of dimension dmodel = 512. Decoder: The decoder is also composed of a stack of N = 6identical layers.'}, {'document': '/content/1706.03762v7.pdf', 'page': 3, 'chunk_id': 1, 'chunk_text': 'Decoder: The decoder is also composed of a stack of N = 6identical layers. In addition to the two\nsub-layers in each encoder layer, the decoder inserts a third sub-layer, which performs multi-head\nattention over the output of the encoder stack. Similar to the encoder, we employ residual connections\naround each of the sub-layers, followed by layer normalization. We also modify the self-attention\nsub-layer in the decoder stack to prevent positions from attending to subsequent positions. This\nmasking, combined with fact that the output embeddings are offset by one position, ensures that the\npredictions for position i can depend only on the known outputs at positions less than i. 3.2 Attention\nAn attention function can be described as mapping a query and a set of key-value pairs to an output,\nwhere the query, keys, values, and output are all vectors. The output is computed as a weighted sum\n3'}, {'document': '/content/1706.03762v7.pdf', 'page': 4, 'chunk_id': 0, 'chunk_text': 'Scaled Dot-Product Attention\n Multi-Head Attention\nFigure 2: (left) Scaled Dot-Product Attention. (right) Multi-Head Attention consists of several\nattention layers running in parallel. of the values, where the weight assigned to each value is computed by a compatibility function of the\nquery with the corresponding key. 3.2.1 Scaled Dot-Product Attention\nWe call our particular attention "Scaled Dot-Product Attention" (Figure 2). The input consists of\nqueries and keys of dimension dk, and values of dimension dv. We compute the dot products of the\nquery with all keys, divide each by √dk, and apply a softmax function to obtain the weights on the\nvalues. In practice, we compute the attention function on a set of queries simultaneously, packed together\ninto a matrix Q. The keys and values are also packed together into matrices K and V .'}, {'document': '/content/1706.03762v7.pdf', 'page': 4, 'chunk_id': 1, 'chunk_text': 'The keys and values are also packed together into matrices K and V . We compute\nthe matrix of outputs as:\nAttention(Q, K, V) = softmax(QK T√dk )V (1)\nThe two most commonly used attention functions are additive attention [2], and dot-product (multi-\nplicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor\nof 1√dk . Additive attention computes the compatibility function using a feed-forward network witha single hidden layer. While the two are similar in theoretical complexity, dot-product attention is\nmuch faster and more space-efficient in practice, since it can be implemented using highly optimized\nmatrix multiplication code. While for small values of dk the two mechanisms perform similarly, additive attention outperforms\ndot product attention without scaling for larger values of dk [3].'}, {'document': '/content/1706.03762v7.pdf', 'page': 4, 'chunk_id': 2, 'chunk_text': 'While for small values of dk the two mechanisms perform similarly, additive attention outperforms\ndot product attention without scaling for larger values of dk [3]. We suspect that for large values of\ndk, the dot products grow large in magnitude, pushing the softmax function into regions where it has\nextremely small gradients 4. To counteract this effect, we scale the dot products by 1√dk . 3.2.2 Multi-Head Attention\nInstead of performing a single attention function with dmodel-dimensional keys, values and queries,\nwe found it beneficial to linearly project the queries, keys and values h times with different, learned\nlinear projections to dk, dk and dv dimensions, respectively. On each of these projected versions of\nqueries, keys and values we then perform the attention function in parallel, yielding dv-dimensional\n4To illustrate why the dot products get large, assume that the components of q and k are independent random\nvariables with mean 0 and variance 1.'}, {'document': '/content/1706.03762v7.pdf', 'page': 4, 'chunk_id': 3, 'chunk_text': 'On each of these projected versions of\nqueries, keys and values we then perform the attention function in parallel, yielding dv-dimensional\n4To illustrate why the dot products get large, assume that the components of q and k are independent random\nvariables with mean 0 and variance 1. Then their dot product, q · k = Pdki=1 qiki, has mean 0 and variance dk. 4'}, {'document': '/content/1706.03762v7.pdf', 'page': 5, 'chunk_id': 0, 'chunk_text': 'output values. These are concatenated and once again projected, resulting in the final values, as\ndepicted in Figure 2. Multi-head attention allows the model to jointly attend to information from different representation\nsubspaces at different positions. With a single attention head, averaging inhibits this. MultiHead(Q, K, V) = Concat(head1, ...,headh)W O\nwhere headi = Attention(QW Qi , KWKi , V WVi )\nWhere the projections are parameter matricesW Qi ∈ Rdmodel×dk, W Ki ∈ Rdmodel×dk, W Vi ∈ Rdmodel×dv\nand W O ∈ Rhdv×dmodel. In this work we employ h = 8 parallel attention layers, or heads. For each of these we use\ndk = dv = dmodel/h = 64. Due to the reduced dimension of each head, the total computational cost\nis similar to that of single-head attention with full dimensionality.'}, {'document': '/content/1706.03762v7.pdf', 'page': 5, 'chunk_id': 1, 'chunk_text': 'Due to the reduced dimension of each head, the total computational cost\nis similar to that of single-head attention with full dimensionality. 3.2.3 Applications of Attention in our Model\nThe Transformer uses multi-head attention in three different ways:\n• In "encoder-decoder attention" layers, the queries come from the previous decoder layer,\nand the memory keys and values come from the output of the encoder. This allows every\nposition in the decoder to attend over all positions in the input sequence. This mimics the\ntypical encoder-decoder attention mechanisms in sequence-to-sequence models such as\n[38, 2, 9]. • The encoder contains self-attention layers. In a self-attention layer all of the keys, values\nand queries come from the same place, in this case, the output of the previous layer in the\nencoder. Each position in the encoder can attend to all positions in the previous layer of the\nencoder.'}, {'document': '/content/1706.03762v7.pdf', 'page': 5, 'chunk_id': 2, 'chunk_text': 'Each position in the encoder can attend to all positions in the previous layer of the\nencoder. • Similarly, self-attention layers in the decoder allow each position in the decoder to attend to\nall positions in the decoder up to and including that position. We need to prevent leftward\ninformation flow in the decoder to preserve the auto-regressive property. We implement this\ninside of scaled dot-product attention by masking out (setting to −∞) all values in the input\nof the softmax which correspond to illegal connections. See Figure 2. 3.3 Position-wise Feed-Forward Networks\nIn addition to attention sub-layers, each of the layers in our encoder and decoder contains a fully\nconnected feed-forward network, which is applied to each position separately and identically. This\nconsists of two linear transformations with a ReLU activation in between.'}, {'document': '/content/1706.03762v7.pdf', 'page': 5, 'chunk_id': 3, 'chunk_text': 'This\nconsists of two linear transformations with a ReLU activation in between. FFN(x) = max(0, xW1 + b1)W2 + b2 (2)\nWhile the linear transformations are the same across different positions, they use different parameters\nfrom layer to layer. Another way of describing this is as two convolutions with kernel size 1. The dimensionality of input and output is dmodel = 512, and the inner-layer has dimensionality\ndf f= 2048. 3.4 Embeddings and Softmax\nSimilarly to other sequence transduction models, we use learned embeddings to convert the input\ntokens and output tokens to vectors of dimension dmodel. We also use the usual learned linear transfor-\nmation and softmax function to convert the decoder output to predicted next-token probabilities. In\nour model, we share the same weight matrix between the two embedding layers and the pre-softmax\nlinear transformation, similar to [30]. In the embedding layers, we multiply those weights by √dmodel. 5'}, {'document': '/content/1706.03762v7.pdf', 'page': 6, 'chunk_id': 0, 'chunk_text': 'Table 1: Maximum path lengths, per-layer complexity and minimum number of sequential operations\nfor different layer types. n is the sequence length, d is the representation dimension, k is the kernel\nsize of convolutions and r the size of the neighborhood in restricted self-attention. Layer Type Complexity per Layer Sequential Maximum Path Length\nOperations\nSelf-Attention O(n2 · d) O(1) O(1)\nRecurrent O(n · d2) O(n) O(n)\nConvolutional O(k · n · d2) O(1) O(logk(n))\nSelf-Attention (restricted) O(r · n · d) O(1) O(n/r)\n3.5 Positional Encoding\nSince our model contains no recurrence and no convolution, in order for the model to make use of the\norder of the sequence, we must inject some information about the relative or absolute position of the\ntokens in the sequence. To this end, we add "posi

In [10]:
# def chunk_documents(cleaned_documents, chunk_size=1000, overlap=200):
#   chunk = []
#   for doc in cleaned_documents:
#     text = doc["text"]
#     start = 0
#     chunk_id = 0
#     while start < len(text):
#       end = start+chunk_size
#       chunk_text = text[start:end]

#       chunk.append(
#           {
#             "document":doc["document"],
#             "page":doc["page"],
#             "chunk_id":chunk_id,
#             "chunk_text":chunk_text
#           }
#       )
#       chunk_id +=1
#       start = start + (chunk_size-overlap)
#   return chunk

In [11]:
# from transformers import AutoTokenizer

# def token_based_chuncking(cleaned_doc,checkpoint,token_size=200, overlap=30):
#   tokenizer = AutoTokenizer.from_pretrained(checkpoint)
#   results = []
#   for doc in cleaned_doc:
#     text = doc["text"]
#     start = 0
#     chunk_id = 0
#     token_ids  = tokenizer.encode(text)
#     while start< len(token_ids) :
#       tokenized = token_ids[start:start+token_size]
#       decoded_text = tokenizer.decode(tokenized)
#       results.append({
#             "document":doc["document"],
#             "page":doc["page"],
#             "chunk_id":chunk_id,
#             "chunk_text":decoded_text})
#       start += token_size - overlap
#       chunk_id+=1
#   return results

In [12]:
def create_embeddings(model,active_corpus):
  chunk_list = []
  for chunk in active_corpus:
    chunk_list.append(chunk["chunk_text"])

  vectors = model.encode(chunk_list)
  return vectors

In [13]:
import numpy as np

from rank_bm25 import BM25Okapi

def build_bm25_index(active_corpus):
    tokenized_corpus = []

    for result in active_corpus:
        text = result["chunk_text"]
        text = text.lower()
        text = text.split()
        tokenized_corpus.append(text)

    bm25_index = BM25Okapi(tokenized_corpus)

    return bm25_index

In [14]:
from nltk.tokenize import sent_tokenize

def create_child_chunks(active_corpus, child_size=300):
    child_chunks = []

    for parent_index, parent in enumerate(active_corpus):

        parent_text = parent["chunk_text"]
        sentences = sent_tokenize(parent_text)

        current_chunk = []

        for sentence in sentences:

            if not current_chunk:
                current_chunk.append(sentence)
                continue

            current_text = " ".join(current_chunk)

            if len(current_text) + len(sentence) + 1 <= child_size:
                current_chunk.append(sentence)

            else:
                child_chunks.append({
                    "child_text": " ".join(current_chunk),
                    "parent_index": parent_index,
                    "document": parent["document"],
                    "page": parent["page"]
                })

                current_chunk = [sentence]

        # save the final child
        if current_chunk:
            child_chunks.append({
                "child_text": " ".join(current_chunk),
                "parent_index": parent_index,
                "document": parent["document"],
                "page": parent["page"]
            })

    return child_chunks

RETRIEVAL FUNCTIONS

In [15]:
import numpy as np
def compute_cos_similarity(query_vector,document_vector):
  return np.dot(document_vector,query_vector)/(np.linalg.norm(query_vector) *np.linalg.norm(document_vector,axis=1))

In [16]:
def retrieve_top_k(queries,embedded_vectors,model,top_k=20):
  ranked_indicies = []
  for query in queries:
    query_vector = model.encode(query)
    cos_similarity = compute_cos_similarity(query_vector,embedded_vectors)
    sorted_indices = np.argsort(cos_similarity)[::-1]
    top_indices = sorted_indices[:top_k]
    ranked_indicies.append(top_indices)


  return ranked_indicies

In [17]:
def bm25_retrival(queries,bm25_index,top_k=20):
  ranked_indicies = []
  for query in queries:
    query = query.lower()
    query = query.split()
    doc_scores = bm25_index.get_scores(query)
    sorted_list = np.argsort(doc_scores)[::-1]
    sorted_list = sorted_list[:top_k]

    ranked_indicies.append(sorted_list)

  return ranked_indicies

In [18]:
def hybrid_search(rankings, k=60, top_k=20):
    rrf_scores = {}

    for ranking in rankings:
        for rank, chunk_index in enumerate(ranking, start=1):
            chunk_index = int(chunk_index)

            if chunk_index in rrf_scores:
                rrf_scores[chunk_index] += 1 / (k + rank)
            else:
                rrf_scores[chunk_index] = 1 / (k + rank)

    ranked_results = sorted(
        rrf_scores.items(),
        key=lambda item: item[1],
        reverse=True
    )

    return ranked_results[:top_k]

In [19]:
def reranking(query, active_corpus, hybrid_results,reranker, top_k=5):

    cross_encoder_list = []
    candidate_indices = []

    for result in hybrid_results:
        index = result[0]

        candidate_indices.append(index)

        text = active_corpus[index]["chunk_text"]

        cross_encoder_list.append(
            [query, text]
        )

    scores = reranker.predict(cross_encoder_list)

    sorted_positions = scores.argsort()[::-1]

    reranked_results = []

    for position in sorted_positions[:top_k]:
        chunk_index = candidate_indices[position]
        reranker_score = scores[position]

        reranked_results.append(
            (chunk_index, reranker_score)
        )

    return reranked_results

 ADVANCED QUERY FUNCTIONS

In [20]:
import ast
def query_transformation(original_query,conversation_context, generation_model, tokenizer):

    prompt = f"""
You are an AI assistant tasked with reformulating user queries to improve retrieval in a RAG system based on the conversation context provided.

Rewrite this question into 3 to 5 different queries for document retrieval in a python list.

Conversation Context:
{conversation_context}

Original query:
{original_query}

Preserve the original meaning.
Do not answer the question.
Do not introduce new facts.
Return only the list of rewritten queries
"""

    messages = [
        {
            "role": "user",
            "content": prompt
        }
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer(
        formatted_prompt,
        return_tensors="pt"
    ).to(generation_model.device)

    with torch.no_grad():
        outputs = generation_model.generate(
            **inputs,
            max_new_tokens=80,
            do_sample=False
        )

    generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

    rewritten_query = tokenizer.decode(
        generated_tokens,
        skip_special_tokens=True
    ).strip()

    queries = []
    for line in rewritten_query.splitlines():
      line = re.sub(r"^\s*\d+[\.\)]\s*", "", line).strip()

      if line:
          queries.append(line)

    return queries

In [21]:
def query_decomposition(original_query,conversation_context, generation_model, tokenizer):
  prompt = f"""
  Break the user query into independent sub-questions
only if necessary.

Conversation Context:
{conversation_context}

Original query:
{original_query}

Each sub-question should retrieve one distinct piece of evidence.

Preserve the user's intent.
Do not answer the questions.
Do not introduce new facts.
Return only the sub-questions."""

  messages = [
          {
              "role": "user",
              "content": prompt
          }
      ]

  formatted_prompt = tokenizer.apply_chat_template(
          messages,
          tokenize=False,
          add_generation_prompt=True
      )
  inputs = tokenizer(
          formatted_prompt,
          return_tensors="pt"
      ).to(generation_model.device)

  with torch.no_grad():
          outputs = generation_model.generate(
              **inputs,
              max_new_tokens=80,
              do_sample=False
          )

  generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

  rewritten_query = tokenizer.decode(
          generated_tokens,
          skip_special_tokens=True
      ).strip()

  queries = []
  for line in rewritten_query.splitlines():
        line = re.sub(r"^\s*\d+[\.\)]\s*", "", line).strip()

        if line:
            queries.append(line)

  return queries

In [22]:
def hyde(original_query,conversation_context,generation_model,tokenizer,embedding_model):
  prompt = f"""
  Write a short passage that would likely appear in a document
answering this query.
Conversation Context:
{conversation_context}

Original query:
{original_query}


Do not mention that it is hypothetical.
Do not explain the task.
Return only the passage. """

  messages = [
          {
              "role": "user",
              "content": prompt
          }
      ]

  formatted_prompt = tokenizer.apply_chat_template(
          messages,
          tokenize=False,
          add_generation_prompt=True
      )
  inputs = tokenizer(
          formatted_prompt,
          return_tensors="pt"
      ).to(generation_model.device)

  with torch.no_grad():
          outputs = generation_model.generate(
              **inputs,
              max_new_tokens=80,
              do_sample=False
          )

  generated_tokens = outputs[0][inputs["input_ids"].shape[1]:]

  generated_text = tokenizer.decode(
          generated_tokens,
          skip_special_tokens=True
      ).strip()

  vector = embedding_model.encode(generated_text)
  return vector,generated_text

def hyde_retreival (hyde_vector,corpus_embeddings,top_k):
  cos_similarity = compute_cos_similarity(hyde_vector,corpus_embeddings)
  sorted_indices = np.argsort(cos_similarity)[::-1]
  top_indices = sorted_indices[:top_k]
  return top_indices

In [23]:
def filter_by_metadata(active_corpus, document=None, page=None):
    filtered_corpus = []
    original_indices = []

    for i, chunk in enumerate(active_corpus):
        match = True

        if document is not None and chunk["document"] != document:
            match = False

        if page is not None and chunk["page"] != page:
            match = False

        if match:
            filtered_corpus.append(chunk)
            original_indices.append(i)

    return filtered_corpus, original_indices

ADVANCED CONTEXT FUNCTIONS

In [24]:
def parent_child_retrieval(
    query,
    child_corpus,
    child_embeddings,
    embedding_model,
    top_k=5
):
    query_vector = embedding_model.encode(query)

    scores = compute_cos_similarity(
        query_vector,
        child_embeddings
    )

    top_child_indices = np.argsort(scores)[::-1][:top_k]

    parent_indices = []
    seen_parents = set()

    for child_index in top_child_indices:
        parent_index = child_corpus[child_index]["parent_index"]

        if parent_index not in seen_parents:
            parent_indices.append(parent_index)
            seen_parents.add(parent_index)

    return parent_indices

In [25]:
def context_compression(
    parent_indices,
    query,
    active_corpus,
    embedding_model,
    top_k=5
):
    candidates = []

    for parent_index in parent_indices:
        parent = active_corpus[parent_index]

        sentences = sent_tokenize(
            parent["chunk_text"]
        )

        for sentence in sentences:
            candidates.append({
                "text": sentence,
                "parent_index": parent_index,
                "document": parent["document"],
                "page": parent["page"]
            })

    if not candidates:
        return []

    sentence_texts = [
        candidate["text"]
        for candidate in candidates
    ]

    sentence_embeddings = embedding_model.encode(
        sentence_texts
    )

    query_vector = embedding_model.encode(query)

    similarity = compute_cos_similarity(
        query_vector,
        sentence_embeddings
    )

    top_positions = np.argsort(similarity)[::-1][:top_k]

    compressed_context = []

    for position in top_positions:
        item = candidates[position].copy()
        item["score"] = float(similarity[position])

        compressed_context.append(item)

    return compressed_context

In [26]:
def context_from_indices(active_corpus, indices):
    context_items = []

    for index in indices:
        context_items.append({
            "text": active_corpus[index]["chunk_text"],
            "document": active_corpus[index]["document"],
            "page": active_corpus[index]["page"]
        })

    return context_items

INDEX BUILDING

In [28]:
# =========================================================
# INDEX BUILDING - RUN ONCE
# =========================================================

# Load documents
doc = load_document(doc_list)

# Clean documents
doc_cleaned = cleaning(doc)

# Build parent corpus
active_corpus = chunk_documents_sentences(
    doc_cleaned,
    chunk_size=1000
)

print("Parent chunks:", len(active_corpus))


# Create parent embeddings
corpus_embeddings = create_embeddings(
    model,
    active_corpus
)

print("Parent embedding shape:", corpus_embeddings.shape)


# Build BM25 index over complete corpus
bm25_index = build_bm25_index(
    active_corpus
)


# Build child corpus for parent-child retrieval
child_corpus = create_child_chunks(
    active_corpus,
    child_size=300
)

print("Child chunks:", len(child_corpus))


# Create child embeddings
child_texts = [
    child["child_text"]
    for child in child_corpus
]

child_embeddings = model.encode(
    child_texts
)

print("Child embedding shape:", child_embeddings.shape)

Parent chunks: 240
Parent embedding shape: (240, 384)
Child chunks: 860
Child embedding shape: (860, 384)

 QUERY-TIME PIPELINE

In [ ]:
# =========================================================
# QUERY-TIME PIPELINE
# =========================================================

conversation_context = (
    "We are discussing how the Transformer decoder works."
)

original_query = """
How does the Transformer decoder generate output,
why is masking necessary,
and how does it differ from the encoder?
"""


# =========================================================
# 1. QUERY DECOMPOSITION
# =========================================================

retrieval_queries = query_decomposition(
    original_query,
    conversation_context,
    generation_model,
    tokenizer
)

print("Retrieval queries:")

for q in retrieval_queries:
    print("-", q)


# =========================================================
# 2. OPTIONAL METADATA FILTER
# =========================================================

target_document = "/content/1706.03762v7.pdf"

if target_document is not None:

    search_corpus, original_indices = filter_by_metadata(
        active_corpus,
        document=target_document
    )

    search_embeddings = corpus_embeddings[
        original_indices
    ]

    search_bm25_index = build_bm25_index(
        search_corpus
    )

else:

    search_corpus = active_corpus

    original_indices = np.arange(
        len(active_corpus)
    )

    search_embeddings = corpus_embeddings

    search_bm25_index = bm25_index


print("Search chunks:", len(search_corpus))


# =========================================================
# 3. DENSE RETRIEVAL
# =========================================================

dense_local_rankings = retrieve_top_k(
    retrieval_queries,
    search_embeddings,
    model,
    top_k=20
)

dense_rankings = []

for ranking in dense_local_rankings:

    converted = [
        int(original_indices[index])
        for index in ranking
    ]

    dense_rankings.append(converted)


# =========================================================
# 4. BM25 RETRIEVAL
# =========================================================

bm25_local_rankings = bm25_retrival(
    retrieval_queries,
    search_bm25_index,
    top_k=20
)

bm25_rankings = []

for ranking in bm25_local_rankings:

    converted = [
        int(original_indices[index])
        for index in ranking
    ]

    bm25_rankings.append(converted)


# =========================================================
# 5. COLLECT RANKINGS FOR RRF
# =========================================================

all_rankings = (
    dense_rankings
    +
    bm25_rankings
)


# =========================================================
# 6. OPTIONAL HYDE
# =========================================================

use_hyde = False

if use_hyde:

    hyde_vector, hypothetical_document = hyde(
        original_query,
        conversation_context,
        generation_model,
        tokenizer,
        model
    )

    hyde_local_indices = hyde_retreival(
        hyde_vector,
        search_embeddings,
        top_k=20
    )

    hyde_ranking = [
        int(original_indices[index])
        for index in hyde_local_indices
    ]

    all_rankings.append(
        hyde_ranking
    )


# =========================================================
# 7. RRF
# =========================================================

hybrid_results = hybrid_search(
    all_rankings,
    k=60,
    top_k=20
)


# =========================================================
# 8. RERANK
# =========================================================

reranked_results = reranking(
    original_query,
    active_corpus,
    hybrid_results,
    reranker,
    top_k=5
)

final_indices = [
    result[0]
    for result in reranked_results
]


# =========================================================
# 9. CREATE FINAL CONTEXT
# =========================================================

final_context = context_from_indices(
    active_corpus,
    final_indices
)


# =========================================================
# 10. GENERATION
# =========================================================

answer = generation(
    original_query,
    final_context,
    generation_model,
    tokenizer
)

print("\nFinal answer:")
print(answer)

Retrieval queries:
- How does the Transformer decoder generate output?
- Why is masking necessary in the Transformer decoder?
- How does the Transformer decoder differ from the encoder?
Search chunks: 53

Final answer:
The Transformer decoder generates output through a process involving multiple steps, including residual connections, layer normalization, and multi-head attention. Masking is necessary because it prevents positions from attending to subsequent positions, ensuring that predictions for position \(i\) can depend only on the known outputs at positions less than \(i\).

Compared to the encoder, the main differences lie in their architectures and functions:
- **Encoder**: Composed of a stack of \(N = 6\) identical layers, each containing two sub-layers. The first sub-layer is a multi-head self-attention mechanism, while the second is a simple, position-wise fully connected feed-forward network.
- **Decoder**: Also composed of a stack of \(N = 6\) identical layers, but differs in that it includes a third sub-layer performing multi-head attention over the output of the encoder stack. Additionally, the decoder employs residual connections around each sub-layer, followed by layer normalization. It modifies the self-attention sub-layer in the decoder stack to prevent positions from attending to subsequent positions, combining this with the fact that the output embeddings are offset by one position, ensuring that the predictions for position \(i\) can depend only on the known outputs at positions less than \(i\).

In [ ]:
# =========================================================
# PARENT-CHILD + CONTEXT COMPRESSION TEST
# =========================================================

query = "Why is masking necessary in the Transformer decoder?"


# Retrieve small children → return large parents
parent_indices = parent_child_retrieval(
    query,
    child_corpus,
    child_embeddings,
    model,
    top_k=5
)

print("Retrieved parents:", parent_indices)


# Compress the parent context
compressed_context = context_compression(
    parent_indices,
    query,
    active_corpus,
    model,
    top_k=5
)


print("\nCompressed context:")

for item in compressed_context:
    print("Score:", item["score"])
    print("Document:", item["document"])
    print("Page:", item["page"])
    print("Text:", item["text"])
    print("-----")


# Generate using compressed context
compressed_answer = generation(
    query,
    compressed_context,
    generation_model,
    tokenizer
)

print("\nCompressed-context answer:")
print(compressed_answer)

Retrieved parents: [12, 93, 9, 7]

Compressed context:
Score: 0.512485921382904
Document: /content/1706.03762v7.pdf
Page: 3
Text: This
masking, combined with fact that the output embeddings are offset by one position, ensures that the
predictions for position i can depend only on the known outputs at positions less than i.
-----
Score: 0.4672187864780426
Document: /content/1706.03762v7.pdf
Page: 3
Text: Decoder: The decoder is also composed of a stack of N = 6identical layers.
-----
Score: 0.46523424983024597
Document: /content/2405.07987v5.pdf
Page: 6
Text: Masked Autoencoders (He et al., 2021) optimize randomly
sampled reconstruction tasks.
-----
Score: 0.44674810767173767
Document: /content/1706.03762v7.pdf
Page: 3
Text: In addition to the two
sub-layers in each encoder layer, the decoder inserts a third sub-layer, which performs multi-head
attention over the output of the encoder stack.
-----
Score: 0.4410628080368042
Document: /content/1706.03762v7.pdf
Page: 2
Text: To the best of our knowledge, however, the Transformer is the first transduction model relying
entirely on self-attention to compute representations of its input and output without using sequence-
aligned RNNs or convolution.
-----

Compressed-context answer:
The text states that "this masking, combined with fact that the output embeddings are offset by one position, ensures that the predictions for position i can depend only on the known outputs at positions less than i." This means that masking helps ensure that the decoder's predictions for any given position are influenced solely by the information available up to that point in the sequence.

Evaluation Dataset

In [29]:
eval_dataset = [

    # ---------------- TRANSFORMER PAPER ----------------

    {
        "question": "Why is masking necessary in the Transformer decoder?",
        "type": "semantic",
        "relevant_chunks": [
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 3,
                "chunk_id": 1
            },
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 5,
                "chunk_id": 2
            }
        ],
        "expected_facts": [
            "decoder positions must not attend to future positions",
            "masking preserves autoregressive generation",
            "position i depends only on known earlier outputs"
        ],
        "should_abstain": False
    },

    {
        "question": "How does the Transformer decoder generate an output sequence?",
        "type": "semantic",
        "relevant_chunks": [
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 2,
                "chunk_id": 5
            },
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 2,
                "chunk_id": 6
            }
        ],
        "expected_facts": [
            "decoder generates symbols one element at a time",
            "generation is autoregressive",
            "previously generated symbols are used to generate the next"
        ],
        "should_abstain": False
    },

    {
        "question": "How does the Transformer decoder architecture differ from the encoder?",
        "type": "multi_part",
        "relevant_chunks": [
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 3,
                "chunk_id": 0
            },
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 3,
                "chunk_id": 1
            }
        ],
        "expected_facts": [
            "encoder layers contain self-attention and feed-forward sublayers",
            "decoder adds a third encoder-decoder attention sublayer",
            "decoder self-attention is masked"
        ],
        "should_abstain": False
    },

    {
        "question": "Why does scaled dot-product attention divide by the square root of the key dimension?",
        "type": "detail",
        "relevant_chunks": [
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 4,
                "chunk_id": 2
            }
        ],
        "expected_facts": [
            "large key dimensions produce large dot products",
            "large dot products push softmax toward very small gradients",
            "scaling by the square root of dk counteracts this"
        ],
        "should_abstain": False
    },

    {
        "question": "What advantage does multi-head attention provide over a single attention head?",
        "type": "semantic",
        "relevant_chunks": [
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 5,
                "chunk_id": 0
            }
        ],
        "expected_facts": [
            "multiple heads attend to different representation subspaces",
            "multiple heads can attend to different positions"
        ],
        "should_abstain": False
    },

    {
        "question": "Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?",
        "type": "multi_part",
        "relevant_chunks": [
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 6,
                "chunk_id": 0
            },
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 6,
                "chunk_id": 1
            },
            {
                "document": "/content/1706.03762v7.pdf",
                "page": 6,
                "chunk_id": 2
            }
        ],
        "expected_facts": [
            "the model has no recurrence or convolution to represent order",
            "positional information is added to embeddings",
            "sinusoidal encodings may help learn relative positions",
            "they may extrapolate to longer sequence lengths"
        ],
        "should_abstain": False
    },


    # ---------------- PLATONIC REPRESENTATION PAPER ----------------

    {
        "question": "What is the Platonic Representation Hypothesis?",
        "type": "semantic",
        "relevant_chunks": [
            {
                "document": "/content/2405.07987v5.pdf",
                "page": 2,
                "chunk_id": 0
            },
            {
                "document": "/content/2405.07987v5.pdf",
                "page": 2,
                "chunk_id": 1
            }
        ],
        "expected_facts": [
            "different models may converge toward a shared representation",
            "representations model an underlying reality",
            "alignment is expected to increase with scale and information"
        ],
        "should_abstain": False
    },

    {
        "question": "How do the authors define and measure representational alignment?",
        "type": "detail",
        "relevant_chunks": [
            {
                "document": "/content/2405.07987v5.pdf",
                "page": 2,
                "chunk_id": 5
            },
            {
                "document": "/content/2405.07987v5.pdf",
                "page": 2,
                "chunk_id": 6
            }
        ],
        "expected_facts": [
            "alignment compares similarity structures induced by representations",
            "these similarity structures are represented as kernels",
            "the experiments use a mutual nearest-neighbor metric"
        ],
        "should_abstain": False
    },

    {
        "question": "What limitation prevents representations from different modalities from always converging perfectly?",
        "type": "semantic",
        "relevant_chunks": [
            {
                "document": "/content/2405.07987v5.pdf",
                "page": 10,
                "chunk_id": 1
            },
            {
                "document": "/content/2405.07987v5.pdf",
                "page": 10,
                "chunk_id": 2
            }
        ],
        "expected_facts": [
            "different modalities can contain fundamentally different information",
            "observations may be lossy or non-bijective",
            "alignment can be limited by available mutual information and model capacity"
        ],
        "should_abstain": False
    },


    # ---------------- ASTRONOMY PRH PAPER ----------------

    {
        "question": "Why is astronomy a useful testbed for the Platonic Representation Hypothesis?",
        "type": "semantic",
        "relevant_chunks": [
            {
                "document": "/content/NeurIPS_ML4PS_2025_87.pdf",
                "page": 2,
                "chunk_id": 3
            },
            {
                "document": "/content/NeurIPS_ML4PS_2025_87.pdf",
                "page": 2,
                "chunk_id": 4
            }
        ],
        "expected_facts": [
            "astronomical modalities are different projections of the same physical reality",
            "images spectra and photometry arise from shared physical processes",
            "this allows cross-modal representation convergence to be tested"
        ],
        "should_abstain": False
    },


    # ---------------- UNANSWERABLE ----------------

    {
        "question": "What was the exact financial cost in US dollars of training the Transformer big model?",
        "type": "unanswerable",
        "relevant_chunks": [],
        "expected_facts": [],
        "should_abstain": True
    },

    {
        "question": "According to these papers, what caused the 2008 global financial crisis?",
        "type": "unanswerable",
        "relevant_chunks": [],
        "expected_facts": [],
        "should_abstain": True
    }
]

In [30]:
def resolve_relevant_indices(eval_dataset, active_corpus):

    chunk_lookup = {}

    for index, chunk in enumerate(active_corpus):

        key = (
            chunk["document"],
            chunk["page"],
            chunk["chunk_id"]
        )

        chunk_lookup[key] = index


    for example in eval_dataset:

        relevant_indices = []

        for chunk in example["relevant_chunks"]:

            key = (
                chunk["document"],
                chunk["page"],
                chunk["chunk_id"]
            )

            if key not in chunk_lookup:
                raise ValueError(
                    f"Ground-truth chunk not found: {key}"
                )

            relevant_indices.append(
                chunk_lookup[key]
            )

        example["relevant_indices"] = relevant_indices

    return eval_dataset

In [31]:
eval_dataset = resolve_relevant_indices(
    eval_dataset,
    active_corpus
)

In [32]:
for example in eval_dataset:

    print(example["question"])
    print("Relevant:", example["relevant_indices"])
    print("Abstain:", example["should_abstain"])
    print("-----")

Why is masking necessary in the Transformer decoder?
Relevant: [12, 19]
Abstain: False
-----
How does the Transformer decoder generate an output sequence?
Relevant: [9, 10]
Abstain: False
-----
How does the Transformer decoder architecture differ from the encoder?
Relevant: [11, 12]
Abstain: False
-----
Why does scaled dot-product attention divide by the square root of the key dimension?
Relevant: [15]
Abstain: False
-----
What advantage does multi-head attention provide over a single attention head?
Relevant: [17]
Abstain: False
-----
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?
Relevant: [21, 22, 23]
Abstain: False
-----
What is the Platonic Representation Hypothesis?
Relevant: [58, 59]
Abstain: False
-----
How do the authors define and measure representational alignment?
Relevant: [63, 64]
Abstain: False
-----
What limitation prevents representations from different modalities from always converging perfectly?
Relevant: [117, 118]
Abstain: False
-----
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?
Relevant: [200, 201]
Abstain: False
-----
What was the exact financial cost in US dollars of training the Transformer big model?
Relevant: []
Abstain: True
-----
According to these papers, what caused the 2008 global financial crisis?
Relevant: []
Abstain: True
-----

In [33]:
def hit_at_k(retrieved_indices, relevant_indices, k):
    for index in retrieved_indices[:k]:
        if index in relevant_indices:
            return 1

    return 0

In [34]:
def recall_at_k(retrieved_indices, relevant_indices, k):
  count = 0
  for index in retrieved_indices[:k]:
    if index in relevant_indices:
      count+=1

  number = len(relevant_indices)
  if number == 0:
    return 0
  recall = count/number
  return recall

In [35]:
def reciprocal_rank(retrieved_indices, relevant_indices, k):
    for i, index in enumerate(retrieved_indices[:k]):
        i = i + 1
        if index in relevant_indices:
            mrr = 1 / i
            return mrr

    return 0

In [36]:
# =========================================================
# TEST ONE EVALUATION QUESTION
# =========================================================

example = eval_dataset[0]

original_query = example["question"]
relevant_indices = example["relevant_indices"]

conversation_context = ""

print("Question:")
print(original_query)

print("\nGround-truth relevant indices:")
print(relevant_indices)


# =========================================================
# 1. QUERY DECOMPOSITION
# =========================================================

retrieval_queries = query_decomposition(
    original_query,
    conversation_context,
    generation_model,
    tokenizer
)

print("\nRetrieval queries:")

for q in retrieval_queries:
    print("-", q)


# =========================================================
# 2. OPTIONAL METADATA FILTER
# =========================================================

# Do not use the known ground-truth document during evaluation.
# That would leak information into retrieval.

target_document = None

if target_document is not None:

    search_corpus, original_indices = filter_by_metadata(
        active_corpus,
        document=target_document
    )

    search_embeddings = corpus_embeddings[
        original_indices
    ]

    search_bm25_index = build_bm25_index(
        search_corpus
    )

else:

    search_corpus = active_corpus

    original_indices = np.arange(
        len(active_corpus)
    )

    search_embeddings = corpus_embeddings

    search_bm25_index = bm25_index


print("\nSearch chunks:", len(search_corpus))


# =========================================================
# 3. DENSE RETRIEVAL
# =========================================================

dense_local_rankings = retrieve_top_k(
    retrieval_queries,
    search_embeddings,
    model,
    top_k=20
)

dense_rankings = []

for ranking in dense_local_rankings:

    converted = [
        int(original_indices[index])
        for index in ranking
    ]

    dense_rankings.append(converted)


# =========================================================
# 4. BM25 RETRIEVAL
# =========================================================

bm25_local_rankings = bm25_retrival(
    retrieval_queries,
    search_bm25_index,
    top_k=20
)

bm25_rankings = []

for ranking in bm25_local_rankings:

    converted = [
        int(original_indices[index])
        for index in ranking
    ]

    bm25_rankings.append(converted)


# =========================================================
# 5. COLLECT RANKINGS FOR RRF
# =========================================================

all_rankings = (
    dense_rankings
    +
    bm25_rankings
)


# =========================================================
# 6. OPTIONAL HYDE
# =========================================================

use_hyde = False

if use_hyde:

    hyde_vector, hypothetical_document = hyde(
        original_query,
        conversation_context,
        generation_model,
        tokenizer,
        model
    )

    hyde_local_indices = hyde_retreival(
        hyde_vector,
        search_embeddings,
        top_k=20
    )

    hyde_ranking = [
        int(original_indices[index])
        for index in hyde_local_indices
    ]

    all_rankings.append(
        hyde_ranking
    )


# =========================================================
# 7. RRF
# =========================================================

hybrid_results = hybrid_search(
    all_rankings,
    k=60,
    top_k=20
)

hybrid_indices = [
    result[0]
    for result in hybrid_results
]


# =========================================================
# 8. RERANK
# =========================================================

reranked_results = reranking(
    original_query,
    active_corpus,
    hybrid_results,
    reranker,
    top_k=5
)

final_indices = [
    result[0]
    for result in reranked_results
]


# =========================================================
# 9. HYBRID METRICS
# =========================================================

hybrid_hit_5 = hit_at_k(
    hybrid_indices,
    relevant_indices,
    k=5
)

hybrid_recall_5 = recall_at_k(
    hybrid_indices,
    relevant_indices,
    k=5
)

hybrid_rr_5 = reciprocal_rank(
    hybrid_indices,
    relevant_indices,
    k=5
)


# =========================================================
# 10. RERANKED METRICS
# =========================================================

reranked_hit_5 = hit_at_k(
    final_indices,
    relevant_indices,
    k=5
)

reranked_recall_5 = recall_at_k(
    final_indices,
    relevant_indices,
    k=5
)

reranked_rr_5 = reciprocal_rank(
    final_indices,
    relevant_indices,
    k=5
)


# =========================================================
# 11. RESULTS
# =========================================================

print("\n========================================")
print("EVALUATION RESULT")
print("========================================")

print("\nQuestion:")
print(original_query)

print("\nGround truth:")
print(relevant_indices)


print("\n----------------------------------------")
print("HYBRID RETRIEVAL")
print("----------------------------------------")

print("Top 5:")
print(hybrid_indices[:5])

print("Hit@5:")
print(hybrid_hit_5)

print("Recall@5:")
print(hybrid_recall_5)

print("Reciprocal Rank@5:")
print(hybrid_rr_5)


print("\n----------------------------------------")
print("RERANKED RETRIEVAL")
print("----------------------------------------")

print("Top 5:")
print(final_indices[:5])

print("Hit@5:")
print(reranked_hit_5)

print("Recall@5:")
print(reranked_recall_5)

print("Reciprocal Rank@5:")
print(reranked_rr_5)

Question:
Why is masking necessary in the Transformer decoder?

Ground-truth relevant indices:
[12, 19]

Retrieval queries:
- What is masking in the context of the Transformer decoder?
- Why is it important to mask parts of the input during training?

Search chunks: 240

========================================
EVALUATION RESULT
========================================

Question:
Why is masking necessary in the Transformer decoder?

Ground truth:
[12, 19]

----------------------------------------
HYBRID RETRIEVAL
----------------------------------------
Top 5:
[7, 19, 18, 52, 23]
Hit@5:
1
Recall@5:
0.5
Reciprocal Rank@5:
0.5

----------------------------------------
RERANKED RETRIEVAL
----------------------------------------
Top 5:
[19, 12, 18, 11, 7]
Hit@5:
1
Recall@5:
1.0
Reciprocal Rank@5:
1.0

In [37]:
# =========================================================
# EVALUATE ALL ANSWERABLE QUESTIONS
# =========================================================

evaluation_results = []

conversation_context = ""

for number, example in enumerate(eval_dataset, start=1):

    # Skip unanswerable questions for retrieval metrics
    if example["should_abstain"]:
        continue

    original_query = example["question"]
    relevant_indices = example["relevant_indices"]

    print("\n" + "=" * 70)
    print(f"QUESTION {number}")
    print("=" * 70)
    print(original_query)


    # =====================================================
    # 1. QUERY DECOMPOSITION
    # =====================================================

    retrieval_queries = query_decomposition(
        original_query,
        conversation_context,
        generation_model,
        tokenizer
    )


    # =====================================================
    # 2. SEARCH CORPUS
    # =====================================================

    # No metadata filtering during evaluation
    # because we do not want to leak the correct document.

    search_corpus = active_corpus

    original_indices = np.arange(
        len(active_corpus)
    )

    search_embeddings = corpus_embeddings

    search_bm25_index = bm25_index


    # =====================================================
    # 3. DENSE RETRIEVAL
    # =====================================================

    dense_local_rankings = retrieve_top_k(
        retrieval_queries,
        search_embeddings,
        model,
        top_k=20
    )

    dense_rankings = []

    for ranking in dense_local_rankings:

        converted = [
            int(original_indices[index])
            for index in ranking
        ]

        dense_rankings.append(converted)


    # =====================================================
    # 4. BM25 RETRIEVAL
    # =====================================================

    bm25_local_rankings = bm25_retrival(
        retrieval_queries,
        search_bm25_index,
        top_k=20
    )

    bm25_rankings = []

    for ranking in bm25_local_rankings:

        converted = [
            int(original_indices[index])
            for index in ranking
        ]

        bm25_rankings.append(converted)


    # =====================================================
    # 5. RRF
    # =====================================================

    all_rankings = (
        dense_rankings
        +
        bm25_rankings
    )

    hybrid_results = hybrid_search(
        all_rankings,
        k=60,
        top_k=20
    )

    hybrid_indices = [
        result[0]
        for result in hybrid_results
    ]


    # =====================================================
    # 6. RERANK
    # =====================================================

    reranked_results = reranking(
        original_query,
        active_corpus,
        hybrid_results,
        reranker,
        top_k=5
    )

    final_indices = [
        result[0]
        for result in reranked_results
    ]


    # =====================================================
    # 7. HYBRID METRICS
    # =====================================================

    hybrid_hit = hit_at_k(
        hybrid_indices,
        relevant_indices,
        k=5
    )

    hybrid_recall = recall_at_k(
        hybrid_indices,
        relevant_indices,
        k=5
    )

    hybrid_rr = reciprocal_rank(
        hybrid_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # 8. RERANKED METRICS
    # =====================================================

    reranked_hit = hit_at_k(
        final_indices,
        relevant_indices,
        k=5
    )

    reranked_recall = recall_at_k(
        final_indices,
        relevant_indices,
        k=5
    )

    reranked_rr = reciprocal_rank(
        final_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # 9. SAVE RESULTS
    # =====================================================

    evaluation_results.append({
        "question": original_query,

        "hybrid_hit@5": hybrid_hit,
        "hybrid_recall@5": hybrid_recall,
        "hybrid_rr@5": hybrid_rr,

        "reranked_hit@5": reranked_hit,
        "reranked_recall@5": reranked_recall,
        "reranked_rr@5": reranked_rr
    })


    # =====================================================
    # 10. PRINT QUESTION RESULT
    # =====================================================

    print("\nGround truth:")
    print(relevant_indices)

    print("\nHybrid Top 5:")
    print(hybrid_indices[:5])

    print(
        f"Hybrid -> "
        f"Hit@5: {hybrid_hit} | "
        f"Recall@5: {hybrid_recall:.3f} | "
        f"RR@5: {hybrid_rr:.3f}"
    )

    print("\nReranked Top 5:")
    print(final_indices)

    print(
        f"Reranked -> "
        f"Hit@5: {reranked_hit} | "
        f"Recall@5: {reranked_recall:.3f} | "
        f"RR@5: {reranked_rr:.3f}"
    )


# =========================================================
# OVERALL METRICS
# =========================================================

hybrid_hit_rate = np.mean([
    result["hybrid_hit@5"]
    for result in evaluation_results
])

hybrid_mean_recall = np.mean([
    result["hybrid_recall@5"]
    for result in evaluation_results
])

hybrid_mrr = np.mean([
    result["hybrid_rr@5"]
    for result in evaluation_results
])


reranked_hit_rate = np.mean([
    result["reranked_hit@5"]
    for result in evaluation_results
])

reranked_mean_recall = np.mean([
    result["reranked_recall@5"]
    for result in evaluation_results
])

reranked_mrr = np.mean([
    result["reranked_rr@5"]
    for result in evaluation_results
])


# =========================================================
# FINAL SUMMARY
# =========================================================

print("\n\n" + "=" * 70)
print("OVERALL RETRIEVAL EVALUATION")
print("=" * 70)

print("\nHYBRID")
print(f"Hit Rate@5:    {hybrid_hit_rate:.3f}")
print(f"Mean Recall@5: {hybrid_mean_recall:.3f}")
print(f"MRR@5:         {hybrid_mrr:.3f}")

print("\nHYBRID + RERANKER")
print(f"Hit Rate@5:    {reranked_hit_rate:.3f}")
print(f"Mean Recall@5: {reranked_mean_recall:.3f}")
print(f"MRR@5:         {reranked_mrr:.3f}")

======================================================================
QUESTION 1
======================================================================
Why is masking necessary in the Transformer decoder?

Ground truth:
[12, 19]

Hybrid Top 5:
[7, 19, 18, 52, 23]
Hybrid -> Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.500

Reranked Top 5:
[19, 12, 18, 11, 7]
Reranked -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

======================================================================
QUESTION 2
======================================================================
How does the Transformer decoder generate an output sequence?

Ground truth:
[9, 10]

Hybrid Top 5:
[9, 10, 18, 11, 6]
Hybrid -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

Reranked Top 5:
[10, 9, 18, 20, 12]
Reranked -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

======================================================================
QUESTION 3
======================================================================
How does the Transformer decoder architecture differ from the encoder?

Ground truth:
[11, 12]

Hybrid Top 5:
[18, 11, 12, 9, 19]
Hybrid -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 0.500

Reranked Top 5:
[11, 18, 9, 12, 39]
Reranked -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

======================================================================
QUESTION 4
======================================================================
Why does scaled dot-product attention divide by the square root of the key dimension?

Ground truth:
[15]

Hybrid Top 5:
[13, 14, 19, 2, 35]
Hybrid -> Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

Reranked Top 5:
[13, 15, 16, 14, 19]
Reranked -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 0.500

======================================================================
QUESTION 5
======================================================================
What advantage does multi-head attention provide over a single attention head?

Ground truth:
[17]

Hybrid Top 5:
[17, 13, 18, 15, 8]
Hybrid -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

Reranked Top 5:
[17, 18, 8, 15, 13]
Reranked -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

======================================================================
QUESTION 6
======================================================================
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?

Ground truth:
[21, 22, 23]

Hybrid Top 5:
[22, 23, 21, 130, 141]
Hybrid -> Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

Reranked Top 5:
[22, 23, 36, 18, 34]
Reranked -> Hit@5: 1 | Recall@5: 0.667 | RR@5: 1.000

======================================================================
QUESTION 7
======================================================================
What is the Platonic Representation Hypothesis?

Ground truth:
[58, 59]

Hybrid Top 5:
[58, 102, 61, 53, 181]
Hybrid -> Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

Reranked Top 5:
[58, 61, 103, 53, 56]
Reranked -> Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

======================================================================
QUESTION 8
======================================================================
How do the authors define and measure representational alignment?

Ground truth:
[63, 64]

Hybrid Top 5:
[84, 63, 65, 123, 122]
Hybrid -> Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.500

Reranked Top 5:
[63, 207, 158, 65, 122]
Reranked -> Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

======================================================================
QUESTION 9
======================================================================
What limitation prevents representations from different modalities from always converging perfectly?

Ground truth:
[117, 118]

Hybrid Top 5:
[113, 76, 98, 107, 85]
Hybrid -> Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

Reranked Top 5:
[61, 53, 115, 76, 85]
Reranked -> Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

======================================================================
QUESTION 10
======================================================================
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?

Ground truth:
[200, 201]

Hybrid Top 5:
[56, 181, 58, 100, 102]
Hybrid -> Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

Reranked Top 5:
[199, 194, 200, 193, 58]
Reranked -> Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.333


======================================================================
OVERALL RETRIEVAL EVALUATION
======================================================================

HYBRID
Hit Rate@5:    0.700
Mean Recall@5: 0.550
MRR@5:         0.550

HYBRID + RERANKER
Hit Rate@5:    0.900
Mean Recall@5: 0.717
MRR@5:         0.783

In [38]:
print("\nRelevant chunk ranks:")

for relevant_index in relevant_indices:

    if relevant_index in hybrid_indices:
        hybrid_rank = hybrid_indices.index(relevant_index) + 1
    else:
        hybrid_rank = None

    if relevant_index in final_indices:
        reranked_rank = final_indices.index(relevant_index) + 1
    else:
        reranked_rank = None

    print(
        f"Chunk {relevant_index} | "
        f"Hybrid rank: {hybrid_rank} | "
        f"Reranked rank: {reranked_rank}"
    )

Relevant chunk ranks:
Chunk 200 | Hybrid rank: 16 | Reranked rank: 3
Chunk 201 | Hybrid rank: None | Reranked rank: None

In [40]:
# =========================================================
# DIAGNOSE QUESTION 9
# =========================================================

example = eval_dataset[8]   # Question 9

original_query = example["question"]
relevant_indices = example["relevant_indices"]

conversation_context = ""

print("Question:")
print(original_query)

print("\nGround-truth relevant indices:")
print(relevant_indices)


# =========================================================
# 1. QUERY DECOMPOSITION
# =========================================================

# retrieval_queries = query_decomposition(
#     original_query,
#     conversation_context,
#     generation_model,
#     tokenizer
# )

# print("\nRetrieval queries:")

# for q in retrieval_queries:
#     print("-", q)

# =========================================================
# 1. ORIGINAL QUERY ONLY — NO DECOMPOSITION
# =========================================================

retrieval_queries = [original_query]

print("\nRetrieval queries:")
for q in retrieval_queries:
    print("-", q)

# =========================================================
# 2. SEARCH CORPUS
# =========================================================

# No metadata filtering during evaluation

search_corpus = active_corpus

original_indices = np.arange(
    len(active_corpus)
)

search_embeddings = corpus_embeddings

search_bm25_index = bm25_index

print("\nSearch chunks:", len(search_corpus))


# =========================================================
# 3. DENSE RETRIEVAL
# =========================================================

dense_local_rankings = retrieve_top_k(
    retrieval_queries,
    search_embeddings,
    model,
    top_k=20
)

dense_rankings = []

for ranking in dense_local_rankings:

    converted = [
        int(original_indices[index])
        for index in ranking
    ]

    dense_rankings.append(converted)


# =========================================================
# 4. BM25 RETRIEVAL
# =========================================================

bm25_local_rankings = bm25_retrival(
    retrieval_queries,
    search_bm25_index,
    top_k=20
)

bm25_rankings = []

for ranking in bm25_local_rankings:

    converted = [
        int(original_indices[index])
        for index in ranking
    ]

    bm25_rankings.append(converted)


# =========================================================
# 5. COMBINE RANKINGS
# =========================================================

all_rankings = (
    dense_rankings
    +
    bm25_rankings
)


# =========================================================
# 6. OPTIONAL HYDE
# =========================================================

use_hyde = False

if use_hyde:

    hyde_vector, hypothetical_document = hyde(
        original_query,
        conversation_context,
        generation_model,
        tokenizer,
        model
    )

    hyde_local_indices = hyde_retreival(
        hyde_vector,
        search_embeddings,
        top_k=20
    )

    hyde_ranking = [
        int(original_indices[index])
        for index in hyde_local_indices
    ]

    all_rankings.append(
        hyde_ranking
    )


# =========================================================
# 7. RRF / HYBRID RETRIEVAL
# =========================================================

hybrid_results = hybrid_search(
    all_rankings,
    k=60,
    top_k=20
)

hybrid_indices = [
    result[0]
    for result in hybrid_results
]


# =========================================================
# 8. RERANK
# =========================================================

reranked_results = reranking(
    original_query,
    active_corpus,
    hybrid_results,
    reranker,
    top_k=5
)

final_indices = [
    result[0]
    for result in reranked_results
]


# =========================================================
# 9. METRICS
# =========================================================

hybrid_hit = hit_at_k(
    hybrid_indices,
    relevant_indices,
    k=5
)

hybrid_recall = recall_at_k(
    hybrid_indices,
    relevant_indices,
    k=5
)

hybrid_rr = reciprocal_rank(
    hybrid_indices,
    relevant_indices,
    k=5
)


reranked_hit = hit_at_k(
    final_indices,
    relevant_indices,
    k=5
)

reranked_recall = recall_at_k(
    final_indices,
    relevant_indices,
    k=5
)

reranked_rr = reciprocal_rank(
    final_indices,
    relevant_indices,
    k=5
)


# =========================================================
# 10. FIND RELEVANT CHUNK RANKS
# =========================================================

print("\n" + "=" * 70)
print("QUESTION 9 DIAGNOSTIC")
print("=" * 70)

print("\nQuestion:")
print(original_query)

print("\nGround truth:")
print(relevant_indices)


print("\n----------------------------------------")
print("DENSE RANKINGS")
print("----------------------------------------")

for i, ranking in enumerate(dense_rankings, start=1):
    print(f"Dense query {i}:")
    print(ranking[:20])


print("\n----------------------------------------")
print("BM25 RANKINGS")
print("----------------------------------------")

for i, ranking in enumerate(bm25_rankings, start=1):
    print(f"BM25 query {i}:")
    print(ranking[:20])


print("\n----------------------------------------")
print("HYBRID TOP 20")
print("----------------------------------------")

print(hybrid_indices)


print("\n----------------------------------------")
print("RERANKED TOP 5")
print("----------------------------------------")

print(final_indices)


print("\n----------------------------------------")
print("RELEVANT CHUNK RANKS")
print("----------------------------------------")

for relevant_index in relevant_indices:

    if relevant_index in hybrid_indices:
        hybrid_rank = hybrid_indices.index(relevant_index) + 1
    else:
        hybrid_rank = None

    if relevant_index in final_indices:
        reranked_rank = final_indices.index(relevant_index) + 1
    else:
        reranked_rank = None

    print(
        f"Chunk {relevant_index} | "
        f"Hybrid rank: {hybrid_rank} | "
        f"Reranked rank: {reranked_rank}"
    )


# =========================================================
# 11. CHECK WHETHER EACH RETRIEVER FOUND THE RELEVANT CHUNKS
# =========================================================

print("\n----------------------------------------")
print("WHERE WERE THE RELEVANT CHUNKS FOUND?")
print("----------------------------------------")

for relevant_index in relevant_indices:

    print(f"\nChunk {relevant_index}")

    for i, ranking in enumerate(dense_rankings, start=1):

        if relevant_index in ranking:
            rank = ranking.index(relevant_index) + 1
            print(
                f"  Dense query {i}: rank {rank}"
            )
        else:
            print(
                f"  Dense query {i}: not found"
            )

    for i, ranking in enumerate(bm25_rankings, start=1):

        if relevant_index in ranking:
            rank = ranking.index(relevant_index) + 1
            print(
                f"  BM25 query {i}: rank {rank}"
            )
        else:
            print(
                f"  BM25 query {i}: not found"
            )


# =========================================================
# 12. FINAL METRICS
# =========================================================

print("\n" + "=" * 70)
print("METRICS")
print("=" * 70)

print("\nHybrid")
print(f"Hit@5:    {hybrid_hit}")
print(f"Recall@5: {hybrid_recall:.3f}")
print(f"RR@5:     {hybrid_rr:.3f}")

print("\nHybrid + Reranker")
print(f"Hit@5:    {reranked_hit}")
print(f"Recall@5: {reranked_recall:.3f}")
print(f"RR@5:     {reranked_rr:.3f}")

Question:
What limitation prevents representations from different modalities from always converging perfectly?

Ground-truth relevant indices:
[117, 118]

Retrieval queries:
- What limitation prevents representations from different modalities from always converging perfectly?

Search chunks: 240

======================================================================
QUESTION 9 DIAGNOSTIC
======================================================================

Question:
What limitation prevents representations from different modalities from always converging perfectly?

Ground truth:
[117, 118]

----------------------------------------
DENSE RANKINGS
----------------------------------------
Dense query 1:
[85, 118, 107, 113, 125, 55, 56, 53, 76, 117, 68, 192, 61, 98, 176, 72, 60, 119, 93, 94]

----------------------------------------
BM25 RANKINGS
----------------------------------------
BM25 query 1:
[61, 198, 52, 76, 212, 62, 200, 113, 106, 65, 55, 98, 119, 197, 115, 99, 51, 181, 97, 214]

----------------------------------------
HYBRID TOP 20
----------------------------------------
[113, 76, 61, 55, 98, 119, 85, 118, 198, 107, 52, 125, 212, 62, 56, 200, 53, 106, 117, 65]

----------------------------------------
RERANKED TOP 5
----------------------------------------
[61, 53, 62, 65, 76]

----------------------------------------
RELEVANT CHUNK RANKS
----------------------------------------
Chunk 117 | Hybrid rank: 19 | Reranked rank: None
Chunk 118 | Hybrid rank: 8 | Reranked rank: None

----------------------------------------
WHERE WERE THE RELEVANT CHUNKS FOUND?
----------------------------------------

Chunk 117
  Dense query 1: rank 10
  BM25 query 1: not found

Chunk 118
  Dense query 1: rank 2
  BM25 query 1: not found

======================================================================
METRICS
======================================================================

Hybrid
Hit@5:    0
Recall@5: 0.000
RR@5:     0.000

Hybrid + Reranker
Hit@5:    0
Recall@5: 0.000
RR@5:     0.000

In [41]:
# =========================================================
# RETRIEVAL ABLATION
#
# A. Dense only
# B. BM25 only
# C. Dense + BM25 + RRF
# D. Dense + BM25 + RRF + Reranker
#
# Original query only:
# - NO query decomposition
# - NO HyDE
# - NO metadata filtering
# =========================================================


ablation_results = []


# =========================================================
# LOOP THROUGH EVALUATION DATASET
# =========================================================

for number, example in enumerate(eval_dataset, start=1):

    # -----------------------------------------------------
    # Skip unanswerable questions for retrieval evaluation
    # -----------------------------------------------------

    if example["should_abstain"]:
        continue


    original_query = example["question"]
    relevant_indices = example["relevant_indices"]

    # IMPORTANT:
    # Retrieval functions expect a LIST of queries

    retrieval_queries = [
        original_query
    ]


    print("\n" + "=" * 80)
    print(f"QUESTION {number}")
    print("=" * 80)

    print(original_query)

    print("\nGround truth:")
    print(relevant_indices)


    # =====================================================
    # SEARCH SPACE
    # =====================================================

    # Full corpus.
    # No metadata filtering during evaluation.

    search_corpus = active_corpus

    original_indices = np.arange(
        len(active_corpus)
    )

    search_embeddings = corpus_embeddings

    search_bm25_index = bm25_index


    # =====================================================
    # A. DENSE RETRIEVAL
    # =====================================================

    dense_local_rankings = retrieve_top_k(
        retrieval_queries,
        search_embeddings,
        model,
        top_k=20
    )


    # We only have one query,
    # so take the first ranking.

    dense_local_indices = dense_local_rankings[0]


    dense_indices = [
        int(original_indices[index])
        for index in dense_local_indices
    ]


    # =====================================================
    # B. BM25 RETRIEVAL
    # =====================================================

    bm25_local_rankings = bm25_retrival(
        retrieval_queries,
        search_bm25_index,
        top_k=20
    )


    # Again, one original query only

    bm25_local_indices = bm25_local_rankings[0]


    bm25_indices = [
        int(original_indices[index])
        for index in bm25_local_indices
    ]


    # =====================================================
    # C. HYBRID — DENSE + BM25 + RRF
    # =====================================================

    all_rankings = [
        dense_indices,
        bm25_indices
    ]


    hybrid_results = hybrid_search(
        all_rankings,
        k=60,
        top_k=20
    )


    hybrid_indices = [
        result[0]
        for result in hybrid_results
    ]


    # =====================================================
    # D. HYBRID + RERANKER
    # =====================================================

    reranked_results = reranking(
        original_query,
        active_corpus,
        hybrid_results,
        reranker,
        top_k=5
    )


    reranked_indices = [
        result[0]
        for result in reranked_results
    ]


    # =====================================================
    # DENSE METRICS
    # =====================================================

    dense_hit = hit_at_k(
        dense_indices,
        relevant_indices,
        k=5
    )

    dense_recall = recall_at_k(
        dense_indices,
        relevant_indices,
        k=5
    )

    dense_rr = reciprocal_rank(
        dense_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # BM25 METRICS
    # =====================================================

    bm25_hit = hit_at_k(
        bm25_indices,
        relevant_indices,
        k=5
    )

    bm25_recall = recall_at_k(
        bm25_indices,
        relevant_indices,
        k=5
    )

    bm25_rr = reciprocal_rank(
        bm25_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # HYBRID METRICS
    # =====================================================

    hybrid_hit = hit_at_k(
        hybrid_indices,
        relevant_indices,
        k=5
    )

    hybrid_recall = recall_at_k(
        hybrid_indices,
        relevant_indices,
        k=5
    )

    hybrid_rr = reciprocal_rank(
        hybrid_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # RERANKED METRICS
    # =====================================================

    reranked_hit = hit_at_k(
        reranked_indices,
        relevant_indices,
        k=5
    )

    reranked_recall = recall_at_k(
        reranked_indices,
        relevant_indices,
        k=5
    )

    reranked_rr = reciprocal_rank(
        reranked_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # SAVE RESULTS
    # =====================================================

    ablation_results.append({

        "question": original_query,

        # Dense
        "dense_hit@5": dense_hit,
        "dense_recall@5": dense_recall,
        "dense_rr@5": dense_rr,

        # BM25
        "bm25_hit@5": bm25_hit,
        "bm25_recall@5": bm25_recall,
        "bm25_rr@5": bm25_rr,

        # Hybrid
        "hybrid_hit@5": hybrid_hit,
        "hybrid_recall@5": hybrid_recall,
        "hybrid_rr@5": hybrid_rr,

        # Hybrid + reranker
        "reranked_hit@5": reranked_hit,
        "reranked_recall@5": reranked_recall,
        "reranked_rr@5": reranked_rr
    })


    # =====================================================
    # PRINT PER-QUESTION RESULTS
    # =====================================================

    print("\n----------------------------------------")
    print("DENSE")
    print("----------------------------------------")

    print("Top 5:")
    print(dense_indices[:5])

    print(
        f"Hit@5: {dense_hit} | "
        f"Recall@5: {dense_recall:.3f} | "
        f"RR@5: {dense_rr:.3f}"
    )


    print("\n----------------------------------------")
    print("BM25")
    print("----------------------------------------")

    print("Top 5:")
    print(bm25_indices[:5])

    print(
        f"Hit@5: {bm25_hit} | "
        f"Recall@5: {bm25_recall:.3f} | "
        f"RR@5: {bm25_rr:.3f}"
    )


    print("\n----------------------------------------")
    print("HYBRID — DENSE + BM25 + RRF")
    print("----------------------------------------")

    print("Top 5:")
    print(hybrid_indices[:5])

    print(
        f"Hit@5: {hybrid_hit} | "
        f"Recall@5: {hybrid_recall:.3f} | "
        f"RR@5: {hybrid_rr:.3f}"
    )


    print("\n----------------------------------------")
    print("HYBRID + RERANKER")
    print("----------------------------------------")

    print("Top 5:")
    print(reranked_indices[:5])

    print(
        f"Hit@5: {reranked_hit} | "
        f"Recall@5: {reranked_recall:.3f} | "
        f"RR@5: {reranked_rr:.3f}"
    )


# =========================================================
# AGGREGATE DENSE RESULTS
# =========================================================

dense_hit_rate = np.mean([
    result["dense_hit@5"]
    for result in ablation_results
])

dense_mean_recall = np.mean([
    result["dense_recall@5"]
    for result in ablation_results
])

dense_mrr = np.mean([
    result["dense_rr@5"]
    for result in ablation_results
])


# =========================================================
# AGGREGATE BM25 RESULTS
# =========================================================

bm25_hit_rate = np.mean([
    result["bm25_hit@5"]
    for result in ablation_results
])

bm25_mean_recall = np.mean([
    result["bm25_recall@5"]
    for result in ablation_results
])

bm25_mrr = np.mean([
    result["bm25_rr@5"]
    for result in ablation_results
])


# =========================================================
# AGGREGATE HYBRID RESULTS
# =========================================================

hybrid_hit_rate = np.mean([
    result["hybrid_hit@5"]
    for result in ablation_results
])

hybrid_mean_recall = np.mean([
    result["hybrid_recall@5"]
    for result in ablation_results
])

hybrid_mrr = np.mean([
    result["hybrid_rr@5"]
    for result in ablation_results
])


# =========================================================
# AGGREGATE HYBRID + RERANKER RESULTS
# =========================================================

reranked_hit_rate = np.mean([
    result["reranked_hit@5"]
    for result in ablation_results
])

reranked_mean_recall = np.mean([
    result["reranked_recall@5"]
    for result in ablation_results
])

reranked_mrr = np.mean([
    result["reranked_rr@5"]
    for result in ablation_results
])


# =========================================================
# FINAL ABLATION SUMMARY
# =========================================================

print("\n\n" + "=" * 80)
print("RETRIEVAL ABLATION RESULTS")
print("=" * 80)


print("\nA. DENSE ONLY")
print(f"Hit Rate@5:    {dense_hit_rate:.3f}")
print(f"Mean Recall@5: {dense_mean_recall:.3f}")
print(f"MRR@5:         {dense_mrr:.3f}")


print("\nB. BM25 ONLY")
print(f"Hit Rate@5:    {bm25_hit_rate:.3f}")
print(f"Mean Recall@5: {bm25_mean_recall:.3f}")
print(f"MRR@5:         {bm25_mrr:.3f}")


print("\nC. DENSE + BM25 + RRF")
print(f"Hit Rate@5:    {hybrid_hit_rate:.3f}")
print(f"Mean Recall@5: {hybrid_mean_recall:.3f}")
print(f"MRR@5:         {hybrid_mrr:.3f}")


print("\nD. DENSE + BM25 + RRF + RERANKER")
print(f"Hit Rate@5:    {reranked_hit_rate:.3f}")
print(f"Mean Recall@5: {reranked_mean_recall:.3f}")
print(f"MRR@5:         {reranked_mrr:.3f}")


# =========================================================
# SIMPLE COMPARISON TABLE
# =========================================================

print("\n" + "=" * 80)
print("SUMMARY TABLE")
print("=" * 80)

print(
    f"{'SYSTEM':<35}"
    f"{'HIT@5':<12}"
    f"{'RECALL@5':<15}"
    f"{'MRR@5':<12}"
)

print("-" * 74)

print(
    f"{'Dense':<35}"
    f"{dense_hit_rate:<12.3f}"
    f"{dense_mean_recall:<15.3f}"
    f"{dense_mrr:<12.3f}"
)

print(
    f"{'BM25':<35}"
    f"{bm25_hit_rate:<12.3f}"
    f"{bm25_mean_recall:<15.3f}"
    f"{bm25_mrr:<12.3f}"
)

print(
    f"{'Dense + BM25 + RRF':<35}"
    f"{hybrid_hit_rate:<12.3f}"
    f"{hybrid_mean_recall:<15.3f}"
    f"{hybrid_mrr:<12.3f}"
)

print(
    f"{'Dense + BM25 + RRF + Reranker':<35}"
    f"{reranked_hit_rate:<12.3f}"
    f"{reranked_mean_recall:<15.3f}"
    f"{reranked_mrr:<12.3f}"
)

================================================================================
QUESTION 1
================================================================================
Why is masking necessary in the Transformer decoder?

Ground truth:
[12, 19]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[11, 12, 130, 10, 18]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.500

----------------------------------------
BM25
----------------------------------------
Top 5:
[19, 16, 201, 122, 39]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[19, 11, 18, 23, 85]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[19, 12, 18, 11, 39]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

================================================================================
QUESTION 2
================================================================================
How does the Transformer decoder generate an output sequence?

Ground truth:
[9, 10]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[10, 11, 12, 18, 9]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

----------------------------------------
BM25
----------------------------------------
Top 5:
[12, 9, 18, 11, 10]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 0.500

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[12, 10, 11, 9, 18]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 0.500

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[10, 9, 18, 20, 12]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

================================================================================
QUESTION 3
================================================================================
How does the Transformer decoder architecture differ from the encoder?

Ground truth:
[11, 12]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[11, 18, 12, 34, 10]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

----------------------------------------
BM25
----------------------------------------
Top 5:
[11, 18, 9, 83, 30]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[11, 18, 12, 9, 30]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[11, 18, 9, 12, 19]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

================================================================================
QUESTION 4
================================================================================
Why does scaled dot-product attention divide by the square root of the key dimension?

Ground truth:
[15]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[15, 16, 13, 14, 35]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

----------------------------------------
BM25
----------------------------------------
Top 5:
[13, 19, 14, 29, 2]
Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[13, 15, 14, 19, 16]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 0.500

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[13, 15, 16, 14, 19]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 0.500

================================================================================
QUESTION 5
================================================================================
What advantage does multi-head attention provide over a single attention head?

Ground truth:
[17]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[17, 18, 15, 12, 50]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

----------------------------------------
BM25
----------------------------------------
Top 5:
[8, 13, 17, 15, 12]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 0.333

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[17, 15, 18, 13, 12]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[17, 18, 8, 15, 13]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 1.000

================================================================================
QUESTION 6
================================================================================
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?

Ground truth:
[21, 22, 23]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[22, 130, 11, 34, 23]
Hit@5: 1 | Recall@5: 0.667 | RR@5: 1.000

----------------------------------------
BM25
----------------------------------------
Top 5:
[36, 23, 35, 22, 16]
Hit@5: 1 | Recall@5: 0.667 | RR@5: 0.500

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[22, 23, 30, 11, 179]
Hit@5: 1 | Recall@5: 0.667 | RR@5: 1.000

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[22, 23, 36, 18, 34]
Hit@5: 1 | Recall@5: 0.667 | RR@5: 1.000

================================================================================
QUESTION 7
================================================================================
What is the Platonic Representation Hypothesis?

Ground truth:
[58, 59]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[61, 102, 58, 96, 95]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.333

----------------------------------------
BM25
----------------------------------------
Top 5:
[52, 51, 99, 129, 100]
Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[58, 100, 56, 102, 61]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[58, 61, 53, 56, 181]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

================================================================================
QUESTION 8
================================================================================
How do the authors define and measure representational alignment?

Ground truth:
[63, 64]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[122, 63, 84, 82, 167]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.500

----------------------------------------
BM25
----------------------------------------
Top 5:
[122, 63, 203, 64, 207]
Hit@5: 1 | Recall@5: 1.000 | RR@5: 0.500

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[122, 63, 207, 158, 84]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.500

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[63, 207, 176, 158, 65]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 1.000

================================================================================
QUESTION 9
================================================================================
What limitation prevents representations from different modalities from always converging perfectly?

Ground truth:
[117, 118]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[85, 118, 107, 113, 125]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.500

----------------------------------------
BM25
----------------------------------------
Top 5:
[61, 198, 52, 76, 212]
Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[113, 76, 61, 55, 98]
Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[61, 53, 62, 65, 76]
Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

================================================================================
QUESTION 10
================================================================================
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?

Ground truth:
[200, 201]

----------------------------------------
DENSE
----------------------------------------
Top 5:
[199, 193, 102, 58, 61]
Hit@5: 0 | Recall@5: 0.000 | RR@5: 0.000

----------------------------------------
BM25
----------------------------------------
Top 5:
[199, 121, 194, 200, 193]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.250

----------------------------------------
HYBRID — DENSE + BM25 + RRF
----------------------------------------
Top 5:
[199, 193, 194, 200, 61]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.250

----------------------------------------
HYBRID + RERANKER
----------------------------------------
Top 5:
[199, 194, 200, 193, 58]
Hit@5: 1 | Recall@5: 0.500 | RR@5: 0.333


================================================================================
RETRIEVAL ABLATION RESULTS
================================================================================

A. DENSE ONLY
Hit Rate@5:    0.900
Mean Recall@5: 0.667
MRR@5:         0.683

B. BM25 ONLY
Hit Rate@5:    0.700
Mean Recall@5: 0.517
MRR@5:         0.408

C. DENSE + BM25 + RRF
Hit Rate@5:    0.900
Mean Recall@5: 0.667
MRR@5:         0.675

D. DENSE + BM25 + RRF + RERANKER
Hit Rate@5:    0.900
Mean Recall@5: 0.717
MRR@5:         0.783

================================================================================
SUMMARY TABLE
================================================================================
SYSTEM                             HIT@5       RECALL@5       MRR@5
--------------------------------------------------------------------------
Dense                              0.900       0.667          0.683
BM25                               0.700       0.517          0.408
Dense + BM25 + RRF                 0.900       0.667          0.675
Dense + BM25 + RRF + Reranker      0.900       0.717          0.783

In [42]:
# =========================================================
# RERANKER ABLATION
#
# A. Dense only
# B. Dense + Reranker
# C. Dense + BM25 + RRF
# D. Dense + BM25 + RRF + Reranker
#
# Original query only
# =========================================================


reranker_ablation_results = []


for number, example in enumerate(eval_dataset, start=1):

    # Skip unanswerable questions for retrieval metrics
    if example["should_abstain"]:
        continue


    original_query = example["question"]
    relevant_indices = example["relevant_indices"]

    retrieval_queries = [
        original_query
    ]


    print("\n" + "=" * 80)
    print(f"QUESTION {number}")
    print("=" * 80)

    print(original_query)


    # =====================================================
    # SEARCH SPACE
    # =====================================================

    search_embeddings = corpus_embeddings

    original_indices = np.arange(
        len(active_corpus)
    )

    search_bm25_index = bm25_index


    # =====================================================
    # A. DENSE RETRIEVAL
    # =====================================================

    dense_local_rankings = retrieve_top_k(
        retrieval_queries,
        search_embeddings,
        model,
        top_k=20
    )

    dense_local_indices = dense_local_rankings[0]

    dense_indices = [
        int(original_indices[index])
        for index in dense_local_indices
    ]


    # =====================================================
    # B. DENSE + RERANKER
    # =====================================================

    # reranking() expects candidates in the same format
    # as hybrid_results:
    #
    # (chunk_index, score)
    #
    # Here we only care about supplying the candidate indices.
    # The cross-encoder will calculate its own relevance scores.

    dense_candidates = [
        (index, 0.0)
        for index in dense_indices[:20]
    ]


    dense_reranked_results = reranking(
        original_query,
        active_corpus,
        dense_candidates,
        reranker,
        top_k=5
    )


    dense_reranked_indices = [
        result[0]
        for result in dense_reranked_results
    ]


    # =====================================================
    # BM25 RETRIEVAL
    # =====================================================

    bm25_local_rankings = bm25_retrival(
        retrieval_queries,
        search_bm25_index,
        top_k=20
    )

    bm25_local_indices = bm25_local_rankings[0]

    bm25_indices = [
        int(original_indices[index])
        for index in bm25_local_indices
    ]


    # =====================================================
    # C. HYBRID — DENSE + BM25 + RRF
    # =====================================================

    all_rankings = [
        dense_indices,
        bm25_indices
    ]


    hybrid_results = hybrid_search(
        all_rankings,
        k=60,
        top_k=20
    )


    hybrid_indices = [
        result[0]
        for result in hybrid_results
    ]


    # =====================================================
    # D. HYBRID + RERANKER
    # =====================================================

    hybrid_reranked_results = reranking(
        original_query,
        active_corpus,
        hybrid_results,
        reranker,
        top_k=5
    )


    hybrid_reranked_indices = [
        result[0]
        for result in hybrid_reranked_results
    ]


    # =====================================================
    # A. DENSE METRICS
    # =====================================================

    dense_hit = hit_at_k(
        dense_indices,
        relevant_indices,
        k=5
    )

    dense_recall = recall_at_k(
        dense_indices,
        relevant_indices,
        k=5
    )

    dense_rr = reciprocal_rank(
        dense_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # B. DENSE + RERANKER METRICS
    # =====================================================

    dense_reranked_hit = hit_at_k(
        dense_reranked_indices,
        relevant_indices,
        k=5
    )

    dense_reranked_recall = recall_at_k(
        dense_reranked_indices,
        relevant_indices,
        k=5
    )

    dense_reranked_rr = reciprocal_rank(
        dense_reranked_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # C. HYBRID METRICS
    # =====================================================

    hybrid_hit = hit_at_k(
        hybrid_indices,
        relevant_indices,
        k=5
    )

    hybrid_recall = recall_at_k(
        hybrid_indices,
        relevant_indices,
        k=5
    )

    hybrid_rr = reciprocal_rank(
        hybrid_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # D. HYBRID + RERANKER METRICS
    # =====================================================

    hybrid_reranked_hit = hit_at_k(
        hybrid_reranked_indices,
        relevant_indices,
        k=5
    )

    hybrid_reranked_recall = recall_at_k(
        hybrid_reranked_indices,
        relevant_indices,
        k=5
    )

    hybrid_reranked_rr = reciprocal_rank(
        hybrid_reranked_indices,
        relevant_indices,
        k=5
    )


    # =====================================================
    # SAVE RESULTS
    # =====================================================

    reranker_ablation_results.append({

        "question": original_query,

        "dense_hit": dense_hit,
        "dense_recall": dense_recall,
        "dense_rr": dense_rr,

        "dense_reranked_hit": dense_reranked_hit,
        "dense_reranked_recall": dense_reranked_recall,
        "dense_reranked_rr": dense_reranked_rr,

        "hybrid_hit": hybrid_hit,
        "hybrid_recall": hybrid_recall,
        "hybrid_rr": hybrid_rr,

        "hybrid_reranked_hit": hybrid_reranked_hit,
        "hybrid_reranked_recall": hybrid_reranked_recall,
        "hybrid_reranked_rr": hybrid_reranked_rr
    })


    # =====================================================
    # PRINT PER QUESTION
    # =====================================================

    print("\nGround truth:")
    print(relevant_indices)


    print("\nDENSE")
    print(dense_indices[:5])

    print(
        f"Hit: {dense_hit} | "
        f"Recall: {dense_recall:.3f} | "
        f"RR: {dense_rr:.3f}"
    )


    print("\nDENSE + RERANKER")
    print(dense_reranked_indices)

    print(
        f"Hit: {dense_reranked_hit} | "
        f"Recall: {dense_reranked_recall:.3f} | "
        f"RR: {dense_reranked_rr:.3f}"
    )


    print("\nHYBRID")
    print(hybrid_indices[:5])

    print(
        f"Hit: {hybrid_hit} | "
        f"Recall: {hybrid_recall:.3f} | "
        f"RR: {hybrid_rr:.3f}"
    )


    print("\nHYBRID + RERANKER")
    print(hybrid_reranked_indices)

    print(
        f"Hit: {hybrid_reranked_hit} | "
        f"Recall: {hybrid_reranked_recall:.3f} | "
        f"RR: {hybrid_reranked_rr:.3f}"
    )


# =========================================================
# AGGREGATE FUNCTION
# =========================================================

def average_metric(results, key):

    return np.mean([
        result[key]
        for result in results
    ])


# =========================================================
# A. DENSE
# =========================================================

dense_hit_rate = average_metric(
    reranker_ablation_results,
    "dense_hit"
)

dense_recall = average_metric(
    reranker_ablation_results,
    "dense_recall"
)

dense_mrr = average_metric(
    reranker_ablation_results,
    "dense_rr"
)


# =========================================================
# B. DENSE + RERANKER
# =========================================================

dense_reranked_hit_rate = average_metric(
    reranker_ablation_results,
    "dense_reranked_hit"
)

dense_reranked_recall = average_metric(
    reranker_ablation_results,
    "dense_reranked_recall"
)

dense_reranked_mrr = average_metric(
    reranker_ablation_results,
    "dense_reranked_rr"
)


# =========================================================
# C. HYBRID
# =========================================================

hybrid_hit_rate = average_metric(
    reranker_ablation_results,
    "hybrid_hit"
)

hybrid_recall = average_metric(
    reranker_ablation_results,
    "hybrid_recall"
)

hybrid_mrr = average_metric(
    reranker_ablation_results,
    "hybrid_rr"
)


# =========================================================
# D. HYBRID + RERANKER
# =========================================================

hybrid_reranked_hit_rate = average_metric(
    reranker_ablation_results,
    "hybrid_reranked_hit"
)

hybrid_reranked_recall = average_metric(
    reranker_ablation_results,
    "hybrid_reranked_recall"
)

hybrid_reranked_mrr = average_metric(
    reranker_ablation_results,
    "hybrid_reranked_rr"
)


# =========================================================
# FINAL SUMMARY
# =========================================================

print("\n\n" + "=" * 80)
print("RERANKER ABLATION SUMMARY")
print("=" * 80)


print(
    f"{'SYSTEM':<38}"
    f"{'HIT@5':<12}"
    f"{'RECALL@5':<15}"
    f"{'MRR@5':<12}"
)

print("-" * 77)


print(
    f"{'Dense':<38}"
    f"{dense_hit_rate:<12.3f}"
    f"{dense_recall:<15.3f}"
    f"{dense_mrr:<12.3f}"
)


print(
    f"{'Dense + Reranker':<38}"
    f"{dense_reranked_hit_rate:<12.3f}"
    f"{dense_reranked_recall:<15.3f}"
    f"{dense_reranked_mrr:<12.3f}"
)


print(
    f"{'Dense + BM25 + RRF':<38}"
    f"{hybrid_hit_rate:<12.3f}"
    f"{hybrid_recall:<15.3f}"
    f"{hybrid_mrr:<12.3f}"
)


print(
    f"{'Dense + BM25 + RRF + Reranker':<38}"
    f"{hybrid_reranked_hit_rate:<12.3f}"
    f"{hybrid_reranked_recall:<15.3f}"
    f"{hybrid_reranked_mrr:<12.3f}"
)

================================================================================
QUESTION 1
================================================================================
Why is masking necessary in the Transformer decoder?

Ground truth:
[12, 19]

DENSE
[11, 12, 130, 10, 18]
Hit: 1 | Recall: 0.500 | RR: 0.500

DENSE + RERANKER
[19, 12, 18, 206, 11]
Hit: 1 | Recall: 1.000 | RR: 1.000

HYBRID
[19, 11, 18, 23, 85]
Hit: 1 | Recall: 0.500 | RR: 1.000

HYBRID + RERANKER
[19, 12, 18, 11, 39]
Hit: 1 | Recall: 1.000 | RR: 1.000

================================================================================
QUESTION 2
================================================================================
How does the Transformer decoder generate an output sequence?

Ground truth:
[9, 10]

DENSE
[10, 11, 12, 18, 9]
Hit: 1 | Recall: 1.000 | RR: 1.000

DENSE + RERANKER
[10, 9, 18, 20, 12]
Hit: 1 | Recall: 1.000 | RR: 1.000

HYBRID
[12, 10, 11, 9, 18]
Hit: 1 | Recall: 1.000 | RR: 0.500

HYBRID + RERANKER
[10, 9, 18, 20, 12]
Hit: 1 | Recall: 1.000 | RR: 1.000

================================================================================
QUESTION 3
================================================================================
How does the Transformer decoder architecture differ from the encoder?

Ground truth:
[11, 12]

DENSE
[11, 18, 12, 34, 10]
Hit: 1 | Recall: 1.000 | RR: 1.000

DENSE + RERANKER
[11, 18, 9, 12, 39]
Hit: 1 | Recall: 1.000 | RR: 1.000

HYBRID
[11, 18, 12, 9, 30]
Hit: 1 | Recall: 1.000 | RR: 1.000

HYBRID + RERANKER
[11, 18, 9, 12, 19]
Hit: 1 | Recall: 1.000 | RR: 1.000

================================================================================
QUESTION 4
================================================================================
Why does scaled dot-product attention divide by the square root of the key dimension?

Ground truth:
[15]

DENSE
[15, 16, 13, 14, 35]
Hit: 1 | Recall: 1.000 | RR: 1.000

DENSE + RERANKER
[13, 15, 16, 14, 19]
Hit: 1 | Recall: 1.000 | RR: 0.500

HYBRID
[13, 15, 14, 19, 16]
Hit: 1 | Recall: 1.000 | RR: 0.500

HYBRID + RERANKER
[13, 15, 16, 14, 19]
Hit: 1 | Recall: 1.000 | RR: 0.500

================================================================================
QUESTION 5
================================================================================
What advantage does multi-head attention provide over a single attention head?

Ground truth:
[17]

DENSE
[17, 18, 15, 12, 50]
Hit: 1 | Recall: 1.000 | RR: 1.000

DENSE + RERANKER
[17, 18, 8, 15, 13]
Hit: 1 | Recall: 1.000 | RR: 1.000

HYBRID
[17, 15, 18, 13, 12]
Hit: 1 | Recall: 1.000 | RR: 1.000

HYBRID + RERANKER
[17, 18, 8, 15, 13]
Hit: 1 | Recall: 1.000 | RR: 1.000

================================================================================
QUESTION 6
================================================================================
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?

Ground truth:
[21, 22, 23]

DENSE
[22, 130, 11, 34, 23]
Hit: 1 | Recall: 0.667 | RR: 1.000

DENSE + RERANKER
[22, 23, 18, 34, 19]
Hit: 1 | Recall: 0.667 | RR: 1.000

HYBRID
[22, 23, 30, 11, 179]
Hit: 1 | Recall: 0.667 | RR: 1.000

HYBRID + RERANKER
[22, 23, 36, 18, 34]
Hit: 1 | Recall: 0.667 | RR: 1.000

================================================================================
QUESTION 7
================================================================================
What is the Platonic Representation Hypothesis?

Ground truth:
[58, 59]

DENSE
[61, 102, 58, 96, 95]
Hit: 1 | Recall: 0.500 | RR: 0.333

DENSE + RERANKER
[58, 61, 109, 103, 53]
Hit: 1 | Recall: 0.500 | RR: 1.000

HYBRID
[58, 100, 56, 102, 61]
Hit: 1 | Recall: 0.500 | RR: 1.000

HYBRID + RERANKER
[58, 61, 53, 56, 181]
Hit: 1 | Recall: 0.500 | RR: 1.000

================================================================================
QUESTION 8
================================================================================
How do the authors define and measure representational alignment?

Ground truth:
[63, 64]

DENSE
[122, 63, 84, 82, 167]
Hit: 1 | Recall: 0.500 | RR: 0.500

DENSE + RERANKER
[63, 207, 158, 65, 122]
Hit: 1 | Recall: 0.500 | RR: 1.000

HYBRID
[122, 63, 207, 158, 84]
Hit: 1 | Recall: 0.500 | RR: 0.500

HYBRID + RERANKER
[63, 207, 176, 158, 65]
Hit: 1 | Recall: 0.500 | RR: 1.000

================================================================================
QUESTION 9
================================================================================
What limitation prevents representations from different modalities from always converging perfectly?

Ground truth:
[117, 118]

DENSE
[85, 118, 107, 113, 125]
Hit: 1 | Recall: 0.500 | RR: 0.500

DENSE + RERANKER
[61, 53, 76, 85, 119]
Hit: 0 | Recall: 0.000 | RR: 0.000

HYBRID
[113, 76, 61, 55, 98]
Hit: 0 | Recall: 0.000 | RR: 0.000

HYBRID + RERANKER
[61, 53, 62, 65, 76]
Hit: 0 | Recall: 0.000 | RR: 0.000

================================================================================
QUESTION 10
================================================================================
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?

Ground truth:
[200, 201]

DENSE
[199, 193, 102, 58, 61]
Hit: 0 | Recall: 0.000 | RR: 0.000

DENSE + RERANKER
[199, 194, 200, 193, 58]
Hit: 1 | Recall: 0.500 | RR: 0.333

HYBRID
[199, 193, 194, 200, 61]
Hit: 1 | Recall: 0.500 | RR: 0.250

HYBRID + RERANKER
[199, 194, 200, 193, 58]
Hit: 1 | Recall: 0.500 | RR: 0.333


================================================================================
RERANKER ABLATION SUMMARY
================================================================================
SYSTEM                                HIT@5       RECALL@5       MRR@5
-----------------------------------------------------------------------------
Dense                                 0.900       0.667          0.683
Dense + Reranker                      0.900       0.717          0.783
Dense + BM25 + RRF                    0.900       0.667          0.675
Dense + BM25 + RRF + Reranker         0.900       0.717          0.783

In [43]:
#Completeness

# =========================================================
# ANSWER QUALITY TEST — QUESTION 1
# =========================================================

example = eval_dataset[0]

original_query = example["question"]
relevant_indices = example["relevant_indices"]
expected_facts = example["expected_facts"]

retrieval_queries = [original_query]


# =========================================================
# 1. DENSE RETRIEVAL
# =========================================================

dense_local_rankings = retrieve_top_k(
    retrieval_queries,
    corpus_embeddings,
    model,
    top_k=20
)

dense_indices = [
    int(index)
    for index in dense_local_rankings[0]
]


# =========================================================
# 2. PREPARE DENSE CANDIDATES FOR RERANKER
# =========================================================

dense_candidates = [
    (index, 0.0)
    for index in dense_indices
]


# =========================================================
# 3. RERANK
# =========================================================

reranked_results = reranking(
    original_query,
    active_corpus,
    dense_candidates,
    reranker,
    top_k=5
)

final_indices = [
    result[0]
    for result in reranked_results
]


# =========================================================
# 4. CREATE CONTEXT
# =========================================================

final_context = context_from_indices(
    active_corpus,
    final_indices
)


# =========================================================
# 5. GENERATE ANSWER
# =========================================================

answer = generation(
    original_query,
    final_context,
    generation_model,
    tokenizer
)


# =========================================================
# 6. PRINT EVERYTHING
# =========================================================

print("=" * 80)
print("QUESTION")
print("=" * 80)
print(original_query)

print("\n" + "=" * 80)
print("EXPECTED FACTS")
print("=" * 80)

for i, fact in enumerate(expected_facts, start=1):
    print(f"{i}. {fact}")


print("\n" + "=" * 80)
print("RERANKED TOP 5 INDICES")
print("=" * 80)
print(final_indices)


print("\n" + "=" * 80)
print("RETRIEVED CONTEXT")
print("=" * 80)

for i, item in enumerate(final_context, start=1):

    print(f"\n--- Context {i} ---")
    print("Document:", item["document"])
    print("Page:", item["page"])
    print(item["text"])


print("\n" + "=" * 80)
print("GENERATED ANSWER")
print("=" * 80)
print(answer)

================================================================================
QUESTION
================================================================================
Why is masking necessary in the Transformer decoder?

================================================================================
EXPECTED FACTS
================================================================================
1. decoder positions must not attend to future positions
2. masking preserves autoregressive generation
3. position i depends only on known earlier outputs

================================================================================
RERANKED TOP 5 INDICES
================================================================================
[19, 12, 18, 206, 11]

================================================================================
RETRIEVED CONTEXT
================================================================================

--- Context 1 ---
Document: /content/1706.03762v7.pdf
Page: 5
Each position in the encoder can attend to all positions in the previous layer of the
encoder. • Similarly, self-attention layers in the decoder allow each position in the decoder to attend to
all positions in the decoder up to and including that position. We need to prevent leftward
information flow in the decoder to preserve the auto-regressive property. We implement this
inside of scaled dot-product attention by masking out (setting to −∞) all values in the input
of the softmax which correspond to illegal connections. See Figure 2. 3.3 Position-wise Feed-Forward Networks
In addition to attention sub-layers, each of the layers in our encoder and decoder contains a fully
connected feed-forward network, which is applied to each position separately and identically. This
consists of two linear transformations with a ReLU activation in between.

--- Context 2 ---
Document: /content/1706.03762v7.pdf
Page: 3
Decoder: The decoder is also composed of a stack of N = 6identical layers. In addition to the two
sub-layers in each encoder layer, the decoder inserts a third sub-layer, which performs multi-head
attention over the output of the encoder stack. Similar to the encoder, we employ residual connections
around each of the sub-layers, followed by layer normalization. We also modify the self-attention
sub-layer in the decoder stack to prevent positions from attending to subsequent positions. This
masking, combined with fact that the output embeddings are offset by one position, ensures that the
predictions for position i can depend only on the known outputs at positions less than i. 3.2 Attention
An attention function can be described as mapping a query and a set of key-value pairs to an output,
where the query, keys, values, and output are all vectors. The output is computed as a weighted sum
3

--- Context 3 ---
Document: /content/1706.03762v7.pdf
Page: 5
Due to the reduced dimension of each head, the total computational cost
is similar to that of single-head attention with full dimensionality. 3.2.3 Applications of Attention in our Model
The Transformer uses multi-head attention in three different ways:
• In "encoder-decoder attention" layers, the queries come from the previous decoder layer,
and the memory keys and values come from the output of the encoder. This allows every
position in the decoder to attend over all positions in the input sequence. This mimics the
typical encoder-decoder attention mechanisms in sequence-to-sequence models such as
[38, 2, 9]. • The encoder contains self-attention layers. In a self-attention layer all of the keys, values
and queries come from the same place, in this case, the output of the previous layer in the
encoder. Each position in the encoder can attend to all positions in the previous layer of the
encoder.

--- Context 4 ---
Document: /content/NeurIPS_ML4PS_2025_87.pdf
Page: 3
AstroPTv2 is an
autoregressive decoder transformer designed for astronomical applications (Smith et al., 2024). As a
model pre-trained exclusively on astronomical observations, AstroPT’s inclusion tests whether models
pre-trained on specialised datasets converge toward the same representations as models pre-trained
on more general data. Our other astronomy-specific model, Specformer, processes one-dimensional
astronomical spectra via a transformer, and represents an entirely distinct data modality compared
to image-based models (Parker et al., 2024). Specformer’s inclusion tests the most extreme case:
whether models pre-trained on fundamentally different input types adhere to the PRH. Measuring representational alignment. Following the methodology established in the original
PRH work, we measure representational alignment using the mutual k-nearest neighbour (MKNN)
metric (Chechik et al., 2010).

--- Context 5 ---
Document: /content/1706.03762v7.pdf
Page: 3
Figure 1: The Transformer - model architecture. The Transformer follows this overall architecture using stacked self-attention and point-wise, fully
connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1,
respectively. 3.1 Encoder and Decoder Stacks
Encoder: The encoder is composed of a stack of N = 6 identical layers. Each layer has two
sub-layers. The first is a multi-head self-attention mechanism, and the second is a simple, position-
wise fully connected feed-forward network. We employ a residual connection [11] around each of
the two sub-layers, followed by layer normalization [ 1]. That is, the output of each sub-layer is
LayerNorm(x + Sublayer(x)), where Sublayer(x) is the function implemented by the sub-layer
itself. To facilitate these residual connections, all sub-layers in the model, as well as the embedding
layers, produce outputs of dimension dmodel = 512. Decoder: The decoder is also composed of a stack of N = 6identical layers.

================================================================================
GENERATED ANSWER
================================================================================
Masking is necessary in the Transformer decoder because it prevents leftward information flow, preserving the auto-regressive property. Specifically, the text states that "We implement this inside of scaled dot-product attention by masking out (setting to −∞) all values in the input of the softmax which correspond to illegal connections." This ensures that predictions for position i can depend only on the known outputs at positions less than i.

In [44]:
# =========================================================
# ABSTENTION TEST — UNANSWERABLE QUESTION 1
# =========================================================

example = eval_dataset[10]

original_query = example["question"]
should_abstain = example["should_abstain"]

retrieval_queries = [original_query]


# =========================================================
# 1. PRINT QUESTION
# =========================================================

print("=" * 80)
print("QUESTION")
print("=" * 80)

print(original_query)

print("\nExpected abstention:")
print(should_abstain)


# =========================================================
# 2. DENSE RETRIEVAL
# =========================================================

dense_local_rankings = retrieve_top_k(
    retrieval_queries,
    corpus_embeddings,
    model,
    top_k=20
)

dense_indices = [
    int(index)
    for index in dense_local_rankings[0]
]


# =========================================================
# 3. PREPARE CANDIDATES FOR RERANKER
# =========================================================

dense_candidates = [
    (index, 0.0)
    for index in dense_indices
]


# =========================================================
# 4. RERANK
# =========================================================

reranked_results = reranking(
    original_query,
    active_corpus,
    dense_candidates,
    reranker,
    top_k=5
)

final_indices = [
    result[0]
    for result in reranked_results
]


# =========================================================
# 5. CREATE FINAL CONTEXT
# =========================================================

final_context = context_from_indices(
    active_corpus,
    final_indices
)


# =========================================================
# 6. GENERATE ANSWER
# =========================================================

answer = generation(
    original_query,
    final_context,
    generation_model,
    tokenizer
)


# =========================================================
# 7. PRINT RETRIEVAL RESULTS
# =========================================================

print("\n" + "=" * 80)
print("DENSE TOP 20")
print("=" * 80)

print(dense_indices)


print("\n" + "=" * 80)
print("RERANKED TOP 5")
print("=" * 80)

print(final_indices)


# =========================================================
# 8. PRINT RETRIEVED CONTEXT
# =========================================================

print("\n" + "=" * 80)
print("RETRIEVED CONTEXT")
print("=" * 80)

for i, item in enumerate(final_context, start=1):

    print(f"\n--- Context {i} ---")

    print(
        "Document:",
        item["document"]
    )

    print(
        "Page:",
        item["page"]
    )

    print(
        item["text"]
    )


# =========================================================
# 9. PRINT GENERATED ANSWER
# =========================================================

print("\n" + "=" * 80)
print("GENERATED ANSWER")
print("=" * 80)

print(answer)

================================================================================
QUESTION
================================================================================
What was the exact financial cost in US dollars of training the Transformer big model?

Expected abstention:
True

================================================================================
DENSE TOP 20
================================================================================
[33, 31, 30, 32, 34, 130, 1, 94, 11, 97, 40, 37, 2, 39, 29, 18, 92, 154, 215, 98]

================================================================================
RERANKED TOP 5
================================================================================
[32, 31, 30, 1, 33]

================================================================================
RETRIEVED CONTEXT
================================================================================

--- Context 1 ---
Document: /content/1706.03762v7.pdf
Page: 8
Even our base model
surpasses all previously published models and ensembles, at a fraction of the training cost of any of
the competitive models. On the WMT 2014 English-to-French translation task, our big model achieves a BLEU score of 41.0,
outperforming all of the previously published single models, at less than 1/4 the training cost of the
previous state-of-the-art model. The Transformer (big) model trained for English-to-French used
dropout rate Pdrop = 0.1, instead of 0.3. For the base models, we used a single model obtained by averaging the last 5 checkpoints, which
were written at 10-minute intervals. For the big models, we averaged the last 20 checkpoints. We
used beam search with a beam size of 4 and length penalty α = 0.6 [38]. These hyperparameters
were chosen after experimentation on the development set. We set the maximum output length during
inference to input length + 50, but terminate early when possible [38].

--- Context 2 ---
Document: /content/1706.03762v7.pdf
Page: 8
For the base model, we use a rate of
Pdrop = 0.1. Label Smoothing During training, we employed label smoothing of value ϵls = 0.1 [36]. This
hurts perplexity, as the model learns to be more unsure, but improves accuracy and BLEU score. 6 Results
6.1 Machine Translation
On the WMT 2014 English-to-German translation task, the big transformer model (Transformer (big)
in Table 2) outperforms the best previously reported models (including ensembles) by more than 2.0
BLEU, establishing a new state-of-the-art BLEU score of 28.4. The configuration of this model is
listed in the bottom line of Table 3. Training took 3.5 days on 8 P100 GPUs. Even our base model
surpasses all previously published models and ensembles, at a fraction of the training cost of any of
the competitive models.

--- Context 3 ---
Document: /content/1706.03762v7.pdf
Page: 8
Table 2: The Transformer achieves better BLEU scores than previous state-of-the-art models on the
English-to-German and English-to-French newstest2014 tests at a fraction of the training cost. Model
BLEU Training Cost (FLOPs)
EN-DE EN-FR EN-DE EN-FR
ByteNet [18] 23.75
Deep-Att + PosUnk [39] 39.2 1.0 · 1020
GNMT + RL [38] 24.6 39.92 2.3 · 1019 1.4 · 1020
ConvS2S [9] 25.16 40.46 9.6 · 1018 1.5 · 1020
MoE [32] 26.03 40.56 2.0 · 1019 1.2 · 1020
Deep-Att + PosUnk Ensemble [39] 40.4 8.0 · 1020
GNMT + RL Ensemble [38] 26.30 41.16 1.8 · 1020 1.1 · 1021
ConvS2S Ensemble [9] 26.36 41.29 7.7 · 1019 1.2 · 1021
Transformer (base model) 27.3 38.1 3.3 · 1018
Transformer (big) 28.4 41.8 2.3 · 1019
Residual Dropout We apply dropout [33] to the output of each sub-layer, before it is added to the
sub-layer input and normalized. In addition, we apply dropout to the sums of the embeddings and the
positional encodings in both the encoder and decoder stacks. For the base model, we use a rate of
Pdrop = 0.1.

--- Context 4 ---
Document: /content/1706.03762v7.pdf
Page: 1
We propose a new simple network architecture, the Transformer,
based solely on attention mechanisms, dispensing with recurrence and convolutions
entirely. Experiments on two machine translation tasks show these models to
be superior in quality while being more parallelizable and requiring significantly
less time to train. Our model achieves 28.4 BLEU on the WMT 2014 English-
to-German translation task, improving over the existing best results, including
ensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task,
our model establishes a new single-model state-of-the-art BLEU score of 41.8 after
training for 3.5 days on eight GPUs, a small fraction of the training costs of the
best models from the literature. We show that the Transformer generalizes well to
other tasks by applying it successfully to English constituency parsing both with
large and limited training data. ∗Equal contribution. Listing order is random.

--- Context 5 ---
Document: /content/1706.03762v7.pdf
Page: 8
We set the maximum output length during
inference to input length + 50, but terminate early when possible [38]. Table 2 summarizes our results and compares our translation quality and training costs to other model
architectures from the literature. We estimate the number of floating point operations used to train a
model by multiplying the training time, the number of GPUs used, and an estimate of the sustained
single-precision floating-point capacity of each GPU 5. 6.2 Model Variations
To evaluate the importance of different components of the Transformer, we varied our base model
in different ways, measuring the change in performance on English-to-German translation on the
5We used values of 2.8, 3.7, 6.0 and 9.5 TFLOPS for K80, K40, M40 and P100, respectively. 8

================================================================================
GENERATED ANSWER
================================================================================
Based on the provided text, there is no specific mention of the exact financial cost in US dollars of training the Transformer big model. Therefore, I cannot provide an answer based on the given information.

In [45]:
# =========================================================
# GENERATE ANSWERS FOR FULL EVALUATION DATASET
#
# Current default pipeline:
# Query
# → Dense Top-20
# → Reranker Top-5
# → Context
# → Generation
# =========================================================

answer_evaluation_results = []


for number, example in enumerate(eval_dataset, start=1):

    original_query = example["question"]
    expected_facts = example["expected_facts"]
    should_abstain = example["should_abstain"]

    retrieval_queries = [original_query]


    print("\n" + "=" * 80)
    print(f"QUESTION {number}/{len(eval_dataset)}")
    print("=" * 80)
    print(original_query)


    # =====================================================
    # 1. DENSE RETRIEVAL — TOP 20
    # =====================================================

    dense_local_rankings = retrieve_top_k(
        retrieval_queries,
        corpus_embeddings,
        model,
        top_k=20
    )

    dense_indices = [
        int(index)
        for index in dense_local_rankings[0]
    ]


    # =====================================================
    # 2. PREPARE CANDIDATES FOR RERANKER
    # =====================================================

    dense_candidates = [
        (index, 0.0)
        for index in dense_indices
    ]


    # =====================================================
    # 3. RERANK — TOP 5
    # =====================================================

    reranked_results = reranking(
        original_query,
        active_corpus,
        dense_candidates,
        reranker,
        top_k=5
    )

    final_indices = [
        result[0]
        for result in reranked_results
    ]


    # =====================================================
    # 4. BUILD FINAL CONTEXT
    # =====================================================

    final_context = context_from_indices(
        active_corpus,
        final_indices
    )


    # =====================================================
    # 5. GENERATE ANSWER
    # =====================================================

    answer = generation(
        original_query,
        final_context,
        generation_model,
        tokenizer
    )


    # =====================================================
    # 6. SAVE EVERYTHING
    # =====================================================

    answer_evaluation_results.append({

        "question_number": number,

        "question": original_query,

        "expected_facts": expected_facts,

        "should_abstain": should_abstain,

        "dense_top20": dense_indices,

        "reranked_top5": final_indices,

        "context": final_context,

        "answer": answer
    })


    # =====================================================
    # 7. PRINT SHORT RESULT
    # =====================================================

    print("\nReranked Top 5:")
    print(final_indices)

    print("\nExpected abstention:")
    print(should_abstain)

    print("\nGenerated answer:")
    print(answer)


# =========================================================
# FINISHED
# =========================================================

print("\n\n" + "=" * 80)
print("ANSWER GENERATION COMPLETE")
print("=" * 80)

print(
    "Questions evaluated:",
    len(answer_evaluation_results)
)

================================================================================
QUESTION 1/12
================================================================================
Why is masking necessary in the Transformer decoder?

Reranked Top 5:
[19, 12, 18, 206, 11]

Expected abstention:
False

Generated answer:
Masking is necessary in the Transformer decoder because it prevents leftward information flow, preserving the auto-regressive property. Specifically, the text states that "We implement this inside of scaled dot-product attention by masking out (setting to −∞) all values in the input of the softmax which correspond to illegal connections." This ensures that predictions for position i can depend only on the known outputs at positions less than i.

================================================================================
QUESTION 2/12
================================================================================
How does the Transformer decoder generate an output sequence?

Reranked Top 5:
[10, 9, 18, 20, 12]

Expected abstention:
False

Generated answer:
The Transformer decoder generates an output sequence by taking into account the previously generated symbols through self-attention. Specifically, it consumes the output of the encoder's previous layer as part of the input during each step of generation. This allows the decoder to consider the entire history of inputs while predicting the next token in the sequence.

================================================================================
QUESTION 3/12
================================================================================
How does the Transformer decoder architecture differ from the encoder?

Reranked Top 5:
[11, 18, 9, 12, 39]

Expected abstention:
False

Generated answer:
The Transformer's decoder architecture differs from the encoder in several key aspects:

1. **Number of Layers**: Both the encoder and decoder follow a stack of \(N = 6\) identical layers.

2. **Sub-Layers**:
   - **Encoder**: Composed of two sub-layers: a multi-head self-attention mechanism and a simple, position-wise fully connected feed-forward network.
   - **Decoder**: Also composed of six identical layers, but it includes an additional sub-layer after the initial two sub-layers. This sub-layer performs multi-head attention over the output of the entire encoder stack.

3. **Residual Connections and Layer Normalization**:
   - Both the encoder and decoder use residual connections and layer normalization around their respective sub-layers.

4. **Self-Attention Mechanism**:
   - The encoder uses a standard self-attention mechanism across all positions within the encoder stack.
   - The decoder introduces a special self-attention mechanism that attends over the entire output of the encoder stack, allowing every position in the decoder to attend to all positions in the input sequence.

These differences reflect how the Transformer leverages self-attention differently between the encoder and decoder components, enabling more flexible and powerful processing capabilities tailored to the specific needs of each part of the model.

================================================================================
QUESTION 4/12
================================================================================
Why does scaled dot-product attention divide by the square root of the key dimension?

Reranked Top 5:
[13, 15, 16, 14, 19]

Expected abstention:
False

Generated answer:
Scaled dot-product attention divides by the square root of the key dimension because doing so normalizes the dot products across different keys, ensuring they contribute equally to the final output. This normalization helps in balancing the contributions from different parts of the query vector when computing the weighted sum over the keys.

================================================================================
QUESTION 5/12
================================================================================
What advantage does multi-head attention provide over a single attention head?

Reranked Top 5:
[17, 18, 8, 15, 13]

Expected abstention:
False

Generated answer:
Multi-head attention provides an advantage over a single attention head because it allows the model to jointly attend to information from different representation subspaces at different positions. With a single attention head, averaging inhibits this ability, whereas multi-head attention enables the model to process multiple perspectives concurrently.

================================================================================
QUESTION 6/12
================================================================================
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?

Reranked Top 5:
[22, 23, 18, 34, 19]

Expected abstention:
False

Generated answer:
The Transformer needs positional encoding because it helps the model understand the relative positions of tokens within sequences. The authors chose sinusoidal encodings because they hypothesized that these functions might allow the model to easily learn to attend by relative positions, making it easier for the model to attend to nearby positions in the sequence.

================================================================================
QUESTION 7/12
================================================================================
What is the Platonic Representation Hypothesis?

Reranked Top 5:
[58, 61, 109, 103, 53]

Expected abstention:
False

Generated answer:
The Platonic Representation Hypothesis posits that there exists a real world (labeled Z) that generates the data we observe through various sensors like cameras. These measurements can then be projected into textual descriptions or other forms of representations. The hypothesis suggests that representation learning algorithms aim to find vector embeddings that statistically model these measurements and projections, ultimately aligning with the underlying reality represented in Z.

================================================================================
QUESTION 8/12
================================================================================
How do the authors define and measure representational alignment?

Reranked Top 5:
[63, 207, 158, 65, 122]

Expected abstention:
False

Generated answer:
The authors define representational alignment as a measure of the similarity of the similarity structures induced by two representations, specifically through the use of a mutual k-nearest neighbor (MKNN) metric. They provide the mathematical definition of this concept below:

• A representation is a function \( f : X \rightarrow \mathbb{R}^n \) that assigns a feature vector to each input in some data domain \( X \).
• A kernel, \( K : X \times X \rightarrow \mathbb{R} \), characterizes how a representation measures distance/similarity between data points.

To measure representational alignment, the authors follow the methodology established in the original PRH work. Specifically, they use the mutual k-nearest neighbor (MKNN) metric, defined as follows:

\[ \text{MKNN}(z_1, z_2) = \frac{k}{b} \left| \bigcap_{i=1}^{b} N_k(z_i) \right| \]

where:
- \( z_1 \) and \( z_2 \) are embeddings corresponding to the same object viewed by two different instruments or models.
- \( b \) is the number of samples in the mini-batch.
- \( N_k \) is the k-nearest neighbors operation.
- \( | \cdot | \) denotes set cardinality.

They test representational alignment via the MKNN score across astronomical modes (crossmodal) and within a

================================================================================
QUESTION 9/12
================================================================================
What limitation prevents representations from different modalities from always converging perfectly?

Reranked Top 5:
[61, 53, 76, 85, 119]

Expected abstention:
False

Generated answer:
Different sensors and views might capture different information, which may limit their potential to converge to identical representations.

================================================================================
QUESTION 10/12
================================================================================
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?

Reranked Top 5:
[199, 194, 200, 193, 58]

Expected abstention:
False

Generated answer:
Astronomy provides an important testbed for the Platonic Representation Hypothesis because its observations are fundamentally linked through shared physical processes. Galaxies' morphologies, chemical compositions, and integrated properties emerge from the same stellar populations, gas and dust dynamics, and underlying matter distributions. This shared physical origin suggests that foundation models viewing different astronomical modalities should converge toward representations that capture the underlying fundamental physics governing these phenomena.

================================================================================
QUESTION 11/12
================================================================================
What was the exact financial cost in US dollars of training the Transformer big model?

Reranked Top 5:
[32, 31, 30, 1, 33]

Expected abstention:
True

Generated answer:
Based on the provided text, there is no specific mention of the exact financial cost in US dollars of training the Transformer big model. Therefore, I cannot provide an answer based on the given information.

================================================================================
QUESTION 12/12
================================================================================
According to these papers, what caused the 2008 global financial crisis?

Reranked Top 5:
[108, 129, 81, 197, 151]

Expected abstention:
True

Generated answer:
Based on the provided context, I do not have enough information to determine what caused the 2008 global financial crisis. The given texts discuss various topics related to natural language processing, computer vision, and machine learning, but they do not provide details about the causes of the 2008 financial crisis.


================================================================================
ANSWER GENERATION COMPLETE
================================================================================
Questions evaluated: 12

In [46]:
for result in answer_evaluation_results:

    print("\n" + "=" * 80)

    print(
        f"QUESTION {result['question_number']}"
    )

    print("=" * 80)

    print(result["question"])

    print("\nExpected facts:")

    if result["expected_facts"]:

        for fact in result["expected_facts"]:
            print("-", fact)

    else:
        print("None — unanswerable question")

    print(
        "\nShould abstain:",
        result["should_abstain"]
    )

    print("\nGenerated answer:")
    print(result["answer"])

================================================================================
QUESTION 1
================================================================================
Why is masking necessary in the Transformer decoder?

Expected facts:
- decoder positions must not attend to future positions
- masking preserves autoregressive generation
- position i depends only on known earlier outputs

Should abstain: False

Generated answer:
Masking is necessary in the Transformer decoder because it prevents leftward information flow, preserving the auto-regressive property. Specifically, the text states that "We implement this inside of scaled dot-product attention by masking out (setting to −∞) all values in the input of the softmax which correspond to illegal connections." This ensures that predictions for position i can depend only on the known outputs at positions less than i.

================================================================================
QUESTION 2
================================================================================
How does the Transformer decoder generate an output sequence?

Expected facts:
- decoder generates symbols one element at a time
- generation is autoregressive
- previously generated symbols are used to generate the next

Should abstain: False

Generated answer:
The Transformer decoder generates an output sequence by taking into account the previously generated symbols through self-attention. Specifically, it consumes the output of the encoder's previous layer as part of the input during each step of generation. This allows the decoder to consider the entire history of inputs while predicting the next token in the sequence.

================================================================================
QUESTION 3
================================================================================
How does the Transformer decoder architecture differ from the encoder?

Expected facts:
- encoder layers contain self-attention and feed-forward sublayers
- decoder adds a third encoder-decoder attention sublayer
- decoder self-attention is masked

Should abstain: False

Generated answer:
The Transformer's decoder architecture differs from the encoder in several key aspects:

1. **Number of Layers**: Both the encoder and decoder follow a stack of \(N = 6\) identical layers.

2. **Sub-Layers**:
   - **Encoder**: Composed of two sub-layers: a multi-head self-attention mechanism and a simple, position-wise fully connected feed-forward network.
   - **Decoder**: Also composed of six identical layers, but it includes an additional sub-layer after the initial two sub-layers. This sub-layer performs multi-head attention over the output of the entire encoder stack.

3. **Residual Connections and Layer Normalization**:
   - Both the encoder and decoder use residual connections and layer normalization around their respective sub-layers.

4. **Self-Attention Mechanism**:
   - The encoder uses a standard self-attention mechanism across all positions within the encoder stack.
   - The decoder introduces a special self-attention mechanism that attends over the entire output of the encoder stack, allowing every position in the decoder to attend to all positions in the input sequence.

These differences reflect how the Transformer leverages self-attention differently between the encoder and decoder components, enabling more flexible and powerful processing capabilities tailored to the specific needs of each part of the model.

================================================================================
QUESTION 4
================================================================================
Why does scaled dot-product attention divide by the square root of the key dimension?

Expected facts:
- large key dimensions produce large dot products
- large dot products push softmax toward very small gradients
- scaling by the square root of dk counteracts this

Should abstain: False

Generated answer:
Scaled dot-product attention divides by the square root of the key dimension because doing so normalizes the dot products across different keys, ensuring they contribute equally to the final output. This normalization helps in balancing the contributions from different parts of the query vector when computing the weighted sum over the keys.

================================================================================
QUESTION 5
================================================================================
What advantage does multi-head attention provide over a single attention head?

Expected facts:
- multiple heads attend to different representation subspaces
- multiple heads can attend to different positions

Should abstain: False

Generated answer:
Multi-head attention provides an advantage over a single attention head because it allows the model to jointly attend to information from different representation subspaces at different positions. With a single attention head, averaging inhibits this ability, whereas multi-head attention enables the model to process multiple perspectives concurrently.

================================================================================
QUESTION 6
================================================================================
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?

Expected facts:
- the model has no recurrence or convolution to represent order
- positional information is added to embeddings
- sinusoidal encodings may help learn relative positions
- they may extrapolate to longer sequence lengths

Should abstain: False

Generated answer:
The Transformer needs positional encoding because it helps the model understand the relative positions of tokens within sequences. The authors chose sinusoidal encodings because they hypothesized that these functions might allow the model to easily learn to attend by relative positions, making it easier for the model to attend to nearby positions in the sequence.

================================================================================
QUESTION 7
================================================================================
What is the Platonic Representation Hypothesis?

Expected facts:
- different models may converge toward a shared representation
- representations model an underlying reality
- alignment is expected to increase with scale and information

Should abstain: False

Generated answer:
The Platonic Representation Hypothesis posits that there exists a real world (labeled Z) that generates the data we observe through various sensors like cameras. These measurements can then be projected into textual descriptions or other forms of representations. The hypothesis suggests that representation learning algorithms aim to find vector embeddings that statistically model these measurements and projections, ultimately aligning with the underlying reality represented in Z.

================================================================================
QUESTION 8
================================================================================
How do the authors define and measure representational alignment?

Expected facts:
- alignment compares similarity structures induced by representations
- these similarity structures are represented as kernels
- the experiments use a mutual nearest-neighbor metric

Should abstain: False

Generated answer:
The authors define representational alignment as a measure of the similarity of the similarity structures induced by two representations, specifically through the use of a mutual k-nearest neighbor (MKNN) metric. They provide the mathematical definition of this concept below:

• A representation is a function \( f : X \rightarrow \mathbb{R}^n \) that assigns a feature vector to each input in some data domain \( X \).
• A kernel, \( K : X \times X \rightarrow \mathbb{R} \), characterizes how a representation measures distance/similarity between data points.

To measure representational alignment, the authors follow the methodology established in the original PRH work. Specifically, they use the mutual k-nearest neighbor (MKNN) metric, defined as follows:

\[ \text{MKNN}(z_1, z_2) = \frac{k}{b} \left| \bigcap_{i=1}^{b} N_k(z_i) \right| \]

where:
- \( z_1 \) and \( z_2 \) are embeddings corresponding to the same object viewed by two different instruments or models.
- \( b \) is the number of samples in the mini-batch.
- \( N_k \) is the k-nearest neighbors operation.
- \( | \cdot | \) denotes set cardinality.

They test representational alignment via the MKNN score across astronomical modes (crossmodal) and within a

================================================================================
QUESTION 9
================================================================================
What limitation prevents representations from different modalities from always converging perfectly?

Expected facts:
- different modalities can contain fundamentally different information
- observations may be lossy or non-bijective
- alignment can be limited by available mutual information and model capacity

Should abstain: False

Generated answer:
Different sensors and views might capture different information, which may limit their potential to converge to identical representations.

================================================================================
QUESTION 10
================================================================================
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?

Expected facts:
- astronomical modalities are different projections of the same physical reality
- images spectra and photometry arise from shared physical processes
- this allows cross-modal representation convergence to be tested

Should abstain: False

Generated answer:
Astronomy provides an important testbed for the Platonic Representation Hypothesis because its observations are fundamentally linked through shared physical processes. Galaxies' morphologies, chemical compositions, and integrated properties emerge from the same stellar populations, gas and dust dynamics, and underlying matter distributions. This shared physical origin suggests that foundation models viewing different astronomical modalities should converge toward representations that capture the underlying fundamental physics governing these phenomena.

================================================================================
QUESTION 11
================================================================================
What was the exact financial cost in US dollars of training the Transformer big model?

Expected facts:
None — unanswerable question

Should abstain: True

Generated answer:
Based on the provided text, there is no specific mention of the exact financial cost in US dollars of training the Transformer big model. Therefore, I cannot provide an answer based on the given information.

================================================================================
QUESTION 12
================================================================================
According to these papers, what caused the 2008 global financial crisis?

Expected facts:
None — unanswerable question

Should abstain: True

Generated answer:
Based on the provided context, I do not have enough information to determine what caused the 2008 global financial crisis. The given texts discuss various topics related to natural language processing, computer vision, and machine learning, but they do not provide details about the causes of the 2008 financial crisis.

In [48]:
# =========================================================
# CREATE FAITHFULNESS REVIEW REPORT
# =========================================================

report_lines = []

for result in answer_evaluation_results:

    # Faithfulness applies here to answerable questions
    if result["should_abstain"]:
        continue

    report_lines.append("=" * 80)
    report_lines.append(
        f"QUESTION {result['question_number']}"
    )
    report_lines.append("=" * 80)

    report_lines.append(result["question"])

    report_lines.append("\nEXPECTED FACTS:")

    for fact in result["expected_facts"]:
        report_lines.append(
            f"- {fact}"
        )

    report_lines.append("\nRETRIEVED CONTEXT:")

    for i, item in enumerate(
        result["context"],
        start=1
    ):

        report_lines.append(
            f"\n--- Context {i} ---"
        )

        report_lines.append(
            f"Document: {item['document']}"
        )

        report_lines.append(
            f"Page: {item['page']}"
        )

        report_lines.append(
            item["text"]
        )

    report_lines.append(
        "\nGENERATED ANSWER:"
    )

    report_lines.append(
        result["answer"]
    )

    report_lines.append("\n\n")


# =========================================================
# SAVE REPORT
# =========================================================

faithfulness_report = "\n".join(
    report_lines
)

with open(
    "/content/faithfulness_report.txt",
    "w",
    encoding="utf-8"
) as f:

    f.write(faithfulness_report)


print(
    "Saved:",
    "/content/faithfulness_report.txt"
)

Saved: /content/faithfulness_report.txt

In [51]:
# =========================================================
# GENERATE ANSWERS FOR FULL EVALUATION DATASET — V2
#
# Same retrieval pipeline:
# Query
# → Dense Top-20
# → Reranker Top-5
# → Context
#
# Only change:
# generation_v2() instead of generation()
# =========================================================

answer_evaluation_results_v2 = []


for number, example in enumerate(eval_dataset, start=1):

    original_query = example["question"]
    expected_facts = example["expected_facts"]
    should_abstain = example["should_abstain"]

    retrieval_queries = [original_query]


    print("\n" + "=" * 80)
    print(f"QUESTION {number}/{len(eval_dataset)}")
    print("=" * 80)
    print(original_query)


    # =====================================================
    # 1. DENSE RETRIEVAL — TOP 20
    # =====================================================

    dense_local_rankings = retrieve_top_k(
        retrieval_queries,
        corpus_embeddings,
        model,
        top_k=20
    )

    dense_indices = [
        int(index)
        for index in dense_local_rankings[0]
    ]


    # =====================================================
    # 2. PREPARE CANDIDATES FOR RERANKER
    # =====================================================

    dense_candidates = [
        (index, 0.0)
        for index in dense_indices
    ]


    # =====================================================
    # 3. RERANK — TOP 5
    # =====================================================

    reranked_results = reranking(
        original_query,
        active_corpus,
        dense_candidates,
        reranker,
        top_k=5
    )

    final_indices = [
        result[0]
        for result in reranked_results
    ]


    # =====================================================
    # 4. BUILD FINAL CONTEXT
    # =====================================================

    final_context = context_from_indices(
        active_corpus,
        final_indices
    )


    # =====================================================
    # 5. GENERATE ANSWER USING NEW PROMPT
    # =====================================================

    answer = generation(
        original_query,
        final_context,
        generation_model,
        tokenizer
    )


    # =====================================================
    # 6. SAVE RESULTS
    # =====================================================

    answer_evaluation_results_v2.append({

        "question_number": number,

        "question": original_query,

        "expected_facts": expected_facts,

        "should_abstain": should_abstain,

        "dense_top20": dense_indices,

        "reranked_top5": final_indices,

        "context": final_context,

        "answer": answer
    })


    # =====================================================
    # 7. PRINT SHORT RESULT
    # =====================================================

    print("\nReranked Top 5:")
    print(final_indices)

    print("\nExpected abstention:")
    print(should_abstain)

    print("\nGenerated answer:")
    print(answer)


# =========================================================
# FINISHED
# =========================================================

print("\n\n" + "=" * 80)
print("V2 ANSWER GENERATION COMPLETE")
print("=" * 80)

print(
    "Questions evaluated:",
    len(answer_evaluation_results_v2)
)

================================================================================
QUESTION 1/12
================================================================================
Why is masking necessary in the Transformer decoder?

Reranked Top 5:
[19, 12, 18, 206, 11]

Expected abstention:
False

Generated answer:
Masking is necessary in the Transformer decoder because it prevents leftward information flow, preserving the auto-regressive property. Specifically, the text states: "We implement this inside of scaled dot-product attention by masking out (setting to −∞) all values in the input of the softmax which correspond to illegal connections." This ensures that predictions for position i can depend only on the known outputs at positions less than i.

================================================================================
QUESTION 2/12
================================================================================
How does the Transformer decoder generate an output sequence?

Reranked Top 5:
[10, 9, 18, 20, 12]

Expected abstention:
False

Generated answer:
The Transformer decoder generates an output sequence by taking the previously generated symbols as additional input during each step. Specifically, given the encoded representation \( z \), the decoder processes these symbols sequentially to produce the output sequence \( (y_1, \ldots, y_m) \) where each \( y_i \) represents a symbol in the output sequence.

================================================================================
QUESTION 3/12
================================================================================
How does the Transformer decoder architecture differ from the encoder?

Reranked Top 5:
[11, 18, 9, 12, 39]

Expected abstention:
False

Generated answer:
The Transformer decoder architecture differs from the encoder in several key aspects:

1. **Number of Layers**: Both the encoder and decoder consist of stacks of identical layers, but the number of layers is specified differently. The encoder has \(N = 6\) identical layers, while the decoder also has \(N = 6\) identical layers.

2. **Sub-Layers**:
   - **Encoder**: Composed of two sub-layers per layer: a multi-head self-attention mechanism and a simple, position-wise fully connected feed-forward network.
   - **Decoder**: Also composed of two sub-layers per layer: a multi-head self-attention mechanism and a simple, position-wise fully connected feed-forward network. Additionally, there is a third sub-layer inserted after the feed-forward network, performing multi-head attention over the output of the encoder stack.

3. **Residual Connections and Layer Normalization**:
   - Both the encoder and decoder use residual connections and layer normalization around each sub-layer.

4. **Self-Attention Mechanism**:
   - The self-attention mechanism in the decoder is modified to prevent positions from attending to subsequent positions, unlike in the encoder where all keys, values, and queries come from the same place.

These differences reflect how the Transformer handles sequential processing in both directions—forward through the decoder and backward through the encoder—to process sequences more effectively compared to traditional recurrent or convolutional approaches.

================================================================================
QUESTION 4/12
================================================================================
Why does scaled dot-product attention divide by the square root of the key dimension?

Reranked Top 5:
[13, 15, 16, 14, 19]

Expected abstention:
False

Generated answer:
Scaled dot-product attention divides by the square root of the key dimension because doing so normalizes the dot products across different keys, ensuring they contribute equally to the final weighted sum. This normalization helps mitigate issues like exploding gradients when the key dimensions become very large, thus improving stability and performance of the model.

================================================================================
QUESTION 5/12
================================================================================
What advantage does multi-head attention provide over a single attention head?

Reranked Top 5:
[17, 18, 8, 15, 13]

Expected abstention:
False

Generated answer:
Multi-head attention provides the advantage of allowing the model to jointly attend to information from different representation subspaces at different positions. It enables the model to capture multiple perspectives of the input data simultaneously, which enhances its ability to understand complex relationships between elements within sequences.

================================================================================
QUESTION 6/12
================================================================================
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?

Reranked Top 5:
[22, 23, 18, 34, 19]

Expected abstention:
False

Generated answer:
The Transformer needs positional encoding because it helps the model understand the relative positions of tokens within sequences. The authors chose sinusoidal encodings because they hypothesized that these functions might allow the model to easily learn to attend by relative positions, making it easier for the model to attend to distant parts of the sequence.

================================================================================
QUESTION 7/12
================================================================================
What is the Platonic Representation Hypothesis?

Reranked Top 5:
[58, 61, 109, 103, 53]

Expected abstention:
False

Generated answer:
The Platonic Representation Hypothesis posits that there exists a real world (labeled Z) that represents the joint distribution over events in the world that generate the data we observe. It suggests that representation learning algorithms find vector embeddings that statistically model the various measurements and projections, aligning with the underlying reality in Z.

================================================================================
QUESTION 8/12
================================================================================
How do the authors define and measure representational alignment?

Reranked Top 5:
[63, 207, 158, 65, 122]

Expected abstention:
False

Generated answer:
The authors define representational alignment as a measure of the similarity of the similarity structures induced by two representations, specifically through the use of a mutual k-nearest neighbor (MKNN) metric. They provide the mathematical definition of this concept below:

• A representation is a function \( f : X \rightarrow \mathbb{R}^n \) that assigns a feature vector to each input in some data domain \( X \).
• A kernel, \( K : X \times X \rightarrow \mathbb{R} \), characterizes how a representation measures distance/similarity between data points.

To measure representational alignment, they propose using the mutual k-nearest neighbor (MKNN) metric. The MKNN score is defined as follows:

\[ \text{MKNN}(z_1, z_2) = \frac{k}{b} |\bigcap_{i=1}^{b} N_k(\phi_i) \cap N_k(\psi_i)| \]

where:
- \( z_1 \) and \( z_2 \) are two embeddings representing the same object viewed by two different instruments or models.
- \( \phi_i = f(x_i) \) and \( \psi_i = g(y_i) \) are the corresponding features extracted from the embeddings.
- \( b \) is the number of samples in the mini-batch.
- \( N_k \) is the k-nearest neighbors operation.
- \( | \cdot |

================================================================================
QUESTION 9/12
================================================================================
What limitation prevents representations from different modalities from always converging perfectly?

Reranked Top 5:
[61, 53, 76, 85, 119]

Expected abstention:
False

Generated answer:
Different sensors and views might capture different information, which may limit their potential to converge to identical representations.

================================================================================
QUESTION 10/12
================================================================================
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?

Reranked Top 5:
[199, 194, 200, 193, 58]

Expected abstention:
False

Generated answer:
Astronomy provides an important testbed for the Platonic Representation Hypothesis because its observations are fundamentally linked through shared physical processes. Galaxies' morphologies, chemical compositions, and integrated properties emerge from the same stellar populations, gas and dust dynamics, and underlying matter distributions. This shared physical origin suggests that foundation models viewing different astronomical modalities should converge toward representations that capture the underlying fundamental physics governing these phenomena.

================================================================================
QUESTION 11/12
================================================================================
What was the exact financial cost in US dollars of training the Transformer big model?

Reranked Top 5:
[32, 31, 30, 1, 33]

Expected abstention:
True

Generated answer:
I do not know based on the provided documents.

================================================================================
QUESTION 12/12
================================================================================
According to these papers, what caused the 2008 global financial crisis?

Reranked Top 5:
[108, 129, 81, 197, 151]

Expected abstention:
True

Generated answer:
I do not know based on the provided documents.


================================================================================
V2 ANSWER GENERATION COMPLETE
================================================================================
Questions evaluated: 12

In [55]:
# =========================================================
# GENERATION MODEL ABLATION — QWEN 7B
#
# SAME:
# - Questions
# - Dense retrieval
# - Top 20
# - Reranker
# - Top 5 context
# - V2 prompt
#
# ONLY CHANGE:
# Qwen2.5-1.5B → Qwen2.5-7B
# =========================================================

answer_evaluation_results_v3 = []


for result in answer_evaluation_results_v2:

    question = result["question"]
    context = result["context"]


    print("\n" + "=" * 80)
    print(
        f"QUESTION {result['question_number']}/"
        f"{len(answer_evaluation_results_v2)}"
    )
    print("=" * 80)

    print(question)


    # =====================================================
    # GENERATE USING STRONGER MODEL
    # =====================================================

    answer = generation(
        question,
        context,
        generation_model_v3,
        tokenizer_v3
    )


    # =====================================================
    # SAVE RESULT
    # =====================================================

    answer_evaluation_results_v3.append({

        "question_number":
            result["question_number"],

        "question":
            question,

        "expected_facts":
            result["expected_facts"],

        "should_abstain":
            result["should_abstain"],

        # exact same retrieval results
        "dense_top20":
            result["dense_top20"],

        "reranked_top5":
            result["reranked_top5"],

        # exact same context
        "context":
            context,

        # new answer only
        "answer":
            answer
    })


    print("\nGenerated answer:")
    print(answer)


print("\n" + "=" * 80)
print("V3 — 7B GENERATION COMPLETE")
print("=" * 80)

print(
    "Questions evaluated:",
    len(answer_evaluation_results_v3)
)

================================================================================
QUESTION 1/12
================================================================================
Why is masking necessary in the Transformer decoder?

Generated answer:
To preserve the auto-regressive property, masking is necessary in the Transformer decoder to prevent leftward information flow, ensuring that predictions for position i can depend only on the known outputs at positions less than i.

================================================================================
QUESTION 2/12
================================================================================
How does the Transformer decoder generate an output sequence?

Generated answer:
The Transformer decoder generates an output sequence (y1, ..., ym) of symbols one element at a time, consuming the previously generated symbols as additional input when generating the next. Additionally, the decoder includes a third sub-layer that performs multi-head attention over the output of the encoder stack. This process is repeated for each position in the output sequence.

================================================================================
QUESTION 3/12
================================================================================
How does the Transformer decoder architecture differ from the encoder?

Generated answer:
The Transformer decoder architecture differs from the encoder in that it includes a third sub-layer performing multi-head attention over the output of the encoder stack. Additionally, the self-attention sub-layer in the decoder stack is modified to prevent positions from attending to subsequent positions, ensuring that predictions for position i can depend only on the known outputs at positions less than i.

================================================================================
QUESTION 4/12
================================================================================
Why does scaled dot-product attention divide by the square root of the key dimension?

Generated answer:
To counteract the effect of dot products growing large in magnitude for larger values of dk, which pushes the softmax function into regions where it has extremely small gradients, scaled dot-product attention divides the dot products by 1/√dk.

================================================================================
QUESTION 5/12
================================================================================
What advantage does multi-head attention provide over a single attention head?

Generated answer:
Multi-head attention allows the model to jointly attend to information from different representation subspaces at different positions, which a single attention head cannot do due to averaging inhibiting this capability.

================================================================================
QUESTION 6/12
================================================================================
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?

Generated answer:
The Transformer needs positional encoding to allow the model to attend by relative positions. The authors chose sinusoidal encodings because they hypothesized it would allow the model to easily learn to attend by relative positions, since for any fixed offset \( k \), \( PE_{pos+k} \) can be represented as a linear function of \( PE_{pos} \). Additionally, they chose the sinusoidal version because it may allow the model to extrapolate to sequence lengths longer than those encountered during training.

================================================================================
QUESTION 7/12
================================================================================
What is the Platonic Representation Hypothesis?

Generated answer:
The Platonic Representation Hypothesis refers to the idea that representations in AI models are converging towards a shared statistical model of reality, akin to Plato’s concept of an ideal reality. These representations are vector embeddings derived from various measurements and projections of the real world (labeled Z), and they become aligned with the underlying reality. Different sensors and views might capture different information, which may limit their potential to converge to identical representations. Larger models tend to better align with human perception of distances, such as color distances, when trained to predict cooccurrences in text or images.

================================================================================
QUESTION 8/12
================================================================================
How do the authors define and measure representational alignment?

Generated answer:
The authors define representational alignment as a measure of the similarity of the similarity structures induced by two representations, i.e., a similarity metric over kernels. They measure representational alignment using the mutual k-nearest neighbour (MKNN) metric. For two models with representations \( f \) and \( g \), the mutual k-nearest neighbor metric measures the average overlap of their respective nearest neighbor sets. Specifically, for a mini-batch of samples, the features from the two representations are computed, and the nearest neighbor sets for each feature pair are compared to find the average overlap.

================================================================================
QUESTION 9/12
================================================================================
What limitation prevents representations from different modalities from always converging perfectly?

Generated answer:
Different sensors and views might capture different information, which may limit their potential to converge to identical representations.

================================================================================
QUESTION 10/12
================================================================================
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?

Generated answer:
Astronomy is a useful testbed for the Platonic Representation Hypothesis because astronomical observations provide different projections of the same underlying cosmic reality, sharing a fundamental nature and being inherently linked through shared physical processes. Observations like galaxy morphology, chemical composition, and integrated properties all emerge from the same stellar populations, gas and dust dynamics, and underlying matter distributions.

================================================================================
QUESTION 11/12
================================================================================
What was the exact financial cost in US dollars of training the Transformer big model?

Generated answer:
I do not know based on the provided documents. The documents mention the training cost in terms of FLOPs (floating point operations) but do not provide the exact financial cost in US dollars.

================================================================================
QUESTION 12/12
================================================================================
According to these papers, what caused the 2008 global financial crisis?

Generated answer:
I do not know based on the provided documents.

================================================================================
V3 — 7B GENERATION COMPLETE
================================================================================
Questions evaluated: 12

In [56]:
for old, new in zip(
    answer_evaluation_results_v2,
    answer_evaluation_results_v3
):

    print("\n" + "=" * 80)
    print(
        f"QUESTION {old['question_number']}"
    )
    print("=" * 80)

    print(old["question"])

    print("\n--- 1.5B ANSWER ---")
    print(old["answer"])

    print("\n--- 7B ANSWER ---")
    print(new["answer"])

================================================================================
QUESTION 1
================================================================================
Why is masking necessary in the Transformer decoder?

--- 1.5B ANSWER ---
Masking is necessary in the Transformer decoder because it prevents leftward information flow, preserving the auto-regressive property. Specifically, the text states: "We implement this inside of scaled dot-product attention by masking out (setting to −∞) all values in the input of the softmax which correspond to illegal connections." This ensures that predictions for position i can depend only on the known outputs at positions less than i.

--- 7B ANSWER ---
To preserve the auto-regressive property, masking is necessary in the Transformer decoder to prevent leftward information flow, ensuring that predictions for position i can depend only on the known outputs at positions less than i.

================================================================================
QUESTION 2
================================================================================
How does the Transformer decoder generate an output sequence?

--- 1.5B ANSWER ---
The Transformer decoder generates an output sequence by taking the previously generated symbols as additional input during each step. Specifically, given the encoded representation \( z \), the decoder processes these symbols sequentially to produce the output sequence \( (y_1, \ldots, y_m) \) where each \( y_i \) represents a symbol in the output sequence.

--- 7B ANSWER ---
The Transformer decoder generates an output sequence (y1, ..., ym) of symbols one element at a time, consuming the previously generated symbols as additional input when generating the next. Additionally, the decoder includes a third sub-layer that performs multi-head attention over the output of the encoder stack. This process is repeated for each position in the output sequence.

================================================================================
QUESTION 3
================================================================================
How does the Transformer decoder architecture differ from the encoder?

--- 1.5B ANSWER ---
The Transformer decoder architecture differs from the encoder in several key aspects:

1. **Number of Layers**: Both the encoder and decoder consist of stacks of identical layers, but the number of layers is specified differently. The encoder has \(N = 6\) identical layers, while the decoder also has \(N = 6\) identical layers.

2. **Sub-Layers**:
   - **Encoder**: Composed of two sub-layers per layer: a multi-head self-attention mechanism and a simple, position-wise fully connected feed-forward network.
   - **Decoder**: Also composed of two sub-layers per layer: a multi-head self-attention mechanism and a simple, position-wise fully connected feed-forward network. Additionally, there is a third sub-layer inserted after the feed-forward network, performing multi-head attention over the output of the encoder stack.

3. **Residual Connections and Layer Normalization**:
   - Both the encoder and decoder use residual connections and layer normalization around each sub-layer.

4. **Self-Attention Mechanism**:
   - The self-attention mechanism in the decoder is modified to prevent positions from attending to subsequent positions, unlike in the encoder where all keys, values, and queries come from the same place.

These differences reflect how the Transformer handles sequential processing in both directions—forward through the decoder and backward through the encoder—to process sequences more effectively compared to traditional recurrent or convolutional approaches.

--- 7B ANSWER ---
The Transformer decoder architecture differs from the encoder in that it includes a third sub-layer performing multi-head attention over the output of the encoder stack. Additionally, the self-attention sub-layer in the decoder stack is modified to prevent positions from attending to subsequent positions, ensuring that predictions for position i can depend only on the known outputs at positions less than i.

================================================================================
QUESTION 4
================================================================================
Why does scaled dot-product attention divide by the square root of the key dimension?

--- 1.5B ANSWER ---
Scaled dot-product attention divides by the square root of the key dimension because doing so normalizes the dot products across different keys, ensuring they contribute equally to the final weighted sum. This normalization helps mitigate issues like exploding gradients when the key dimensions become very large, thus improving stability and performance of the model.

--- 7B ANSWER ---
To counteract the effect of dot products growing large in magnitude for larger values of dk, which pushes the softmax function into regions where it has extremely small gradients, scaled dot-product attention divides the dot products by 1/√dk.

================================================================================
QUESTION 5
================================================================================
What advantage does multi-head attention provide over a single attention head?

--- 1.5B ANSWER ---
Multi-head attention provides the advantage of allowing the model to jointly attend to information from different representation subspaces at different positions. It enables the model to capture multiple perspectives of the input data simultaneously, which enhances its ability to understand complex relationships between elements within sequences.

--- 7B ANSWER ---
Multi-head attention allows the model to jointly attend to information from different representation subspaces at different positions, which a single attention head cannot do due to averaging inhibiting this capability.

================================================================================
QUESTION 6
================================================================================
Why does the Transformer need positional encoding and why did the authors choose sinusoidal encodings?

--- 1.5B ANSWER ---
The Transformer needs positional encoding because it helps the model understand the relative positions of tokens within sequences. The authors chose sinusoidal encodings because they hypothesized that these functions might allow the model to easily learn to attend by relative positions, making it easier for the model to attend to distant parts of the sequence.

--- 7B ANSWER ---
The Transformer needs positional encoding to allow the model to attend by relative positions. The authors chose sinusoidal encodings because they hypothesized it would allow the model to easily learn to attend by relative positions, since for any fixed offset \( k \), \( PE_{pos+k} \) can be represented as a linear function of \( PE_{pos} \). Additionally, they chose the sinusoidal version because it may allow the model to extrapolate to sequence lengths longer than those encountered during training.

================================================================================
QUESTION 7
================================================================================
What is the Platonic Representation Hypothesis?

--- 1.5B ANSWER ---
The Platonic Representation Hypothesis posits that there exists a real world (labeled Z) that represents the joint distribution over events in the world that generate the data we observe. It suggests that representation learning algorithms find vector embeddings that statistically model the various measurements and projections, aligning with the underlying reality in Z.

--- 7B ANSWER ---
The Platonic Representation Hypothesis refers to the idea that representations in AI models are converging towards a shared statistical model of reality, akin to Plato’s concept of an ideal reality. These representations are vector embeddings derived from various measurements and projections of the real world (labeled Z), and they become aligned with the underlying reality. Different sensors and views might capture different information, which may limit their potential to converge to identical representations. Larger models tend to better align with human perception of distances, such as color distances, when trained to predict cooccurrences in text or images.

================================================================================
QUESTION 8
================================================================================
How do the authors define and measure representational alignment?

--- 1.5B ANSWER ---
The authors define representational alignment as a measure of the similarity of the similarity structures induced by two representations, specifically through the use of a mutual k-nearest neighbor (MKNN) metric. They provide the mathematical definition of this concept below:

• A representation is a function \( f : X \rightarrow \mathbb{R}^n \) that assigns a feature vector to each input in some data domain \( X \).
• A kernel, \( K : X \times X \rightarrow \mathbb{R} \), characterizes how a representation measures distance/similarity between data points.

To measure representational alignment, they propose using the mutual k-nearest neighbor (MKNN) metric. The MKNN score is defined as follows:

\[ \text{MKNN}(z_1, z_2) = \frac{k}{b} |\bigcap_{i=1}^{b} N_k(\phi_i) \cap N_k(\psi_i)| \]

where:
- \( z_1 \) and \( z_2 \) are two embeddings representing the same object viewed by two different instruments or models.
- \( \phi_i = f(x_i) \) and \( \psi_i = g(y_i) \) are the corresponding features extracted from the embeddings.
- \( b \) is the number of samples in the mini-batch.
- \( N_k \) is the k-nearest neighbors operation.
- \( | \cdot |

--- 7B ANSWER ---
The authors define representational alignment as a measure of the similarity of the similarity structures induced by two representations, i.e., a similarity metric over kernels. They measure representational alignment using the mutual k-nearest neighbour (MKNN) metric. For two models with representations \( f \) and \( g \), the mutual k-nearest neighbor metric measures the average overlap of their respective nearest neighbor sets. Specifically, for a mini-batch of samples, the features from the two representations are computed, and the nearest neighbor sets for each feature pair are compared to find the average overlap.

================================================================================
QUESTION 9
================================================================================
What limitation prevents representations from different modalities from always converging perfectly?

--- 1.5B ANSWER ---
Different sensors and views might capture different information, which may limit their potential to converge to identical representations.

--- 7B ANSWER ---
Different sensors and views might capture different information, which may limit their potential to converge to identical representations.

================================================================================
QUESTION 10
================================================================================
Why is astronomy a useful testbed for the Platonic Representation Hypothesis?

--- 1.5B ANSWER ---
Astronomy provides an important testbed for the Platonic Representation Hypothesis because its observations are fundamentally linked through shared physical processes. Galaxies' morphologies, chemical compositions, and integrated properties emerge from the same stellar populations, gas and dust dynamics, and underlying matter distributions. This shared physical origin suggests that foundation models viewing different astronomical modalities should converge toward representations that capture the underlying fundamental physics governing these phenomena.

--- 7B ANSWER ---
Astronomy is a useful testbed for the Platonic Representation Hypothesis because astronomical observations provide different projections of the same underlying cosmic reality, sharing a fundamental nature and being inherently linked through shared physical processes. Observations like galaxy morphology, chemical composition, and integrated properties all emerge from the same stellar populations, gas and dust dynamics, and underlying matter distributions.

================================================================================
QUESTION 11
================================================================================
What was the exact financial cost in US dollars of training the Transformer big model?

--- 1.5B ANSWER ---
I do not know based on the provided documents.

--- 7B ANSWER ---
I do not know based on the provided documents. The documents mention the training cost in terms of FLOPs (floating point operations) but do not provide the exact financial cost in US dollars.

================================================================================
QUESTION 12
================================================================================
According to these papers, what caused the 2008 global financial crisis?

--- 1.5B ANSWER ---
I do not know based on the provided documents.

--- 7B ANSWER ---
I do not know based on the provided documents.

In [57]:
import pandas as pd


# =========================================================
# GENERATION ABLATION SUMMARY
# =========================================================

generation_evaluation_summary = pd.DataFrame([
    {
        "version": "V1",
        "generator": "Qwen2.5-1.5B-Instruct",
        "prompt": "Original",
        "completeness": 0.675,
        "faithfulness": 0.81,
        "correctness": 0.75,
        "abstention": 1.00
    },
    {
        "version": "V2",
        "generator": "Qwen2.5-1.5B-Instruct",
        "prompt": "Improved",
        "completeness": 0.71,
        "faithfulness": 0.84,
        "correctness": 0.83,
        "abstention": 1.00
    },
    {
        "version": "V3",
        "generator": "Qwen2.5-7B-Instruct",
        "prompt": "Improved",
        "completeness": 0.83,
        "faithfulness": 0.97,
        "correctness": 0.95,
        "abstention": 1.00
    }
])

print("GENERATION EVALUATION")
display(generation_evaluation_summary)


# =========================================================
# FINAL CURRENT RAG BASELINE
# =========================================================

final_rag_baseline = pd.DataFrame([
    {
        "retrieval_pipeline": "Dense Top20 -> Reranker Top5",
        "retrieval_hit@5": 0.900,
        "retrieval_recall@5": 0.717,
        "retrieval_mrr@5": 0.783,

        "generator": "Qwen2.5-7B-Instruct",
        "generation_prompt": "V2",

        "answer_completeness": 0.83,
        "answer_faithfulness": 0.97,
        "answer_correctness": 0.95,
        "abstention": 1.00
    }
])

print("\nFINAL CURRENT RAG BASELINE")
display(final_rag_baseline)


# =========================================================
# SAVE TO CSV
# =========================================================

generation_evaluation_summary.to_csv(
    "/content/generation_evaluation_summary.csv",
    index=False
)

final_rag_baseline.to_csv(
    "/content/final_rag_baseline.csv",
    index=False
)

print("\nSaved:")
print("/content/generation_evaluation_summary.csv")
print("/content/final_rag_baseline.csv")

GENERATION EVALUATION

,version,generator,prompt,completeness,faithfulness,correctness,abstention
0,V1,Qwen2.5-1.5B-Instruct,Original,0.675,0.81,0.75,1.0
1,V2,Qwen2.5-1.5B-Instruct,Improved,0.710,0.84,0.83,1.0
2,V3,Qwen2.5-7B-Instruct,Improved,0.830,0.97,0.95,1.0

FINAL CURRENT RAG BASELINE

,retrieval_pipeline,retrieval_hit@5,retrieval_recall@5,retrieval_mrr@5,generator,generation_prompt,answer_completeness,answer_faithfulness,answer_correctness,abstention
0,Dense Top20 -> Reranker Top5,0.9,0.717,0.783,Qwen2.5-7B-Instruct,V2,0.83,0.97,0.95,1.0

Saved:
/content/generation_evaluation_summary.csv
/content/final_rag_baseline.csv